// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                  = new(Query)
	Image              *image
	Meeting            *meeting
	MeetingParticipant *meetingParticipant
	Permission         *permission
	Role               *role
	RolePermission     *rolePermission
	User               *user
	UserRole           *userRole
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Image = &Q.Image
	Meeting = &Q.Meeting
	MeetingParticipant = &Q.MeetingParticipant
	Permission = &Q.Permission
	Role = &Q.Role
	RolePermission = &Q.RolePermission
	User = &Q.User
	UserRole = &Q.UserRole
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                 db,
		Image:              newImage(db, opts...),
		Meeting:            newMeeting(db, opts...),
		MeetingParticipant: newMeetingParticipant(db, opts...),
		Permission:         newPermission(db, opts...),
		Role:               newRole(db, opts...),
		RolePermission:     newRolePermission(db, opts...),
		User:               newUser(db, opts...),
		UserRole:           newUserRole(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Image              image
	Meeting            meeting
	MeetingParticipant meetingParticipant
	Permission         permission
	Role               role
	RolePermission     rolePermission
	User               user
	UserRole           userRole
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Image:              q.Image.clone(db),
		Meeting:            q.Meeting.clone(db),
		MeetingParticipant: q.MeetingParticipant.clone(db),
		Permission:         q.Permission.clone(db),
		Role:               q.Role.clone(db),
		RolePermission:     q.RolePermission.clone(db),
		User:               q.User.clone(db),
		UserRole:           q.UserRole.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Image:              q.Image.replaceDB(db),
		Meeting:            q.Meeting.replaceDB(db),
		MeetingParticipant: q.MeetingParticipant.replaceDB(db),
		Permission:         q.Permission.replaceDB(db),
		Role:               q.Role.replaceDB(db),
		RolePermission:     q.RolePermission.replaceDB(db),
		User:               q.User.replaceDB(db),
		UserRole:           q.UserRole.replaceDB(db),
	}
}

type queryCtx struct {
	Image              IImageDo
	Meeting            IMeetingDo
	MeetingParticipant IMeetingParticipantDo
	Permission         IPermissionDo
	Role               IRoleDo
	RolePermission     IRolePermissionDo
	User               IUserDo
	UserRole           IUserRoleDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Image:              q.Image.WithContext(ctx),
		Meeting:            q.Meeting.WithContext(ctx),
		MeetingParticipant: q.MeetingParticipant.WithContext(ctx),
		Permission:         q.Permission.WithContext(ctx),
		Role:               q.Role.WithContext(ctx),
		RolePermission:     q.RolePermission.WithContext(ctx),
		User:               q.User.WithContext(ctx),
		UserRole:           q.UserRole.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
