// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"fast-gin/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMeetingRoom(db *gorm.DB, opts ...gen.DOOption) meetingRoom {
	_meetingRoom := meetingRoom{}

	_meetingRoom.meetingRoomDo.UseDB(db, opts...)
	_meetingRoom.meetingRoomDo.UseModel(&models.MeetingRoom{})

	tableName := _meetingRoom.meetingRoomDo.TableName()
	_meetingRoom.ALL = field.NewAsterisk(tableName)
	_meetingRoom.ID = field.NewUint(tableName, "id")
	_meetingRoom.CreatedAt = field.NewTime(tableName, "created_at")
	_meetingRoom.UpdatedAt = field.NewTime(tableName, "updated_at")
	_meetingRoom.DeletedAt = field.NewField(tableName, "deleted_at")
	_meetingRoom.RoomNo = field.NewString(tableName, "room_no")
	_meetingRoom.Title = field.NewString(tableName, "title")
	_meetingRoom.CreatorID = field.NewUint(tableName, "creator_id")
	_meetingRoom.RoomStatus = field.NewInt8(tableName, "room_status")
	_meetingRoom.MaxMembers = field.NewInt(tableName, "max_members")

	_meetingRoom.fillFieldMap()

	return _meetingRoom
}

type meetingRoom struct {
	meetingRoomDo meetingRoomDo

	ALL        field.Asterisk
	ID         field.Uint   // 主键ID
	CreatedAt  field.Time   // 创建时间
	UpdatedAt  field.Time   // 更新时间
	DeletedAt  field.Field  // 删除时间
	RoomNo     field.String // 会议号
	Title      field.String // 会议标题
	CreatorID  field.Uint   // 创建者ID
	RoomStatus field.Int8   // 会议状态 0未开始 1进行中 2已结束
	MaxMembers field.Int    // 最大成员数

	fieldMap map[string]field.Expr
}

func (m meetingRoom) Table(newTableName string) *meetingRoom {
	m.meetingRoomDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m meetingRoom) As(alias string) *meetingRoom {
	m.meetingRoomDo.DO = *(m.meetingRoomDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *meetingRoom) updateTableName(table string) *meetingRoom {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")
	m.RoomNo = field.NewString(table, "room_no")
	m.Title = field.NewString(table, "title")
	m.CreatorID = field.NewUint(table, "creator_id")
	m.RoomStatus = field.NewInt8(table, "room_status")
	m.MaxMembers = field.NewInt(table, "max_members")

	m.fillFieldMap()

	return m
}

func (m *meetingRoom) WithContext(ctx context.Context) IMeetingRoomDo {
	return m.meetingRoomDo.WithContext(ctx)
}

func (m meetingRoom) TableName() string { return m.meetingRoomDo.TableName() }

func (m meetingRoom) Alias() string { return m.meetingRoomDo.Alias() }

func (m meetingRoom) Columns(cols ...field.Expr) gen.Columns { return m.meetingRoomDo.Columns(cols...) }

func (m *meetingRoom) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *meetingRoom) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 9)
	m.fieldMap["id"] = m.ID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
	m.fieldMap["room_no"] = m.RoomNo
	m.fieldMap["title"] = m.Title
	m.fieldMap["creator_id"] = m.CreatorID
	m.fieldMap["room_status"] = m.RoomStatus
	m.fieldMap["max_members"] = m.MaxMembers
}

func (m meetingRoom) clone(db *gorm.DB) meetingRoom {
	m.meetingRoomDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m meetingRoom) replaceDB(db *gorm.DB) meetingRoom {
	m.meetingRoomDo.ReplaceDB(db)
	return m
}

type meetingRoomDo struct{ gen.DO }

type IMeetingRoomDo interface {
	gen.SubQuery
	Debug() IMeetingRoomDo
	WithContext(ctx context.Context) IMeetingRoomDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMeetingRoomDo
	WriteDB() IMeetingRoomDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMeetingRoomDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMeetingRoomDo
	Not(conds ...gen.Condition) IMeetingRoomDo
	Or(conds ...gen.Condition) IMeetingRoomDo
	Select(conds ...field.Expr) IMeetingRoomDo
	Where(conds ...gen.Condition) IMeetingRoomDo
	Order(conds ...field.Expr) IMeetingRoomDo
	Distinct(cols ...field.Expr) IMeetingRoomDo
	Omit(cols ...field.Expr) IMeetingRoomDo
	Join(table schema.Tabler, on ...field.Expr) IMeetingRoomDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMeetingRoomDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMeetingRoomDo
	Group(cols ...field.Expr) IMeetingRoomDo
	Having(conds ...gen.Condition) IMeetingRoomDo
	Limit(limit int) IMeetingRoomDo
	Offset(offset int) IMeetingRoomDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMeetingRoomDo
	Unscoped() IMeetingRoomDo
	Create(values ...*models.MeetingRoom) error
	CreateInBatches(values []*models.MeetingRoom, batchSize int) error
	Save(values ...*models.MeetingRoom) error
	First() (*models.MeetingRoom, error)
	Take() (*models.MeetingRoom, error)
	Last() (*models.MeetingRoom, error)
	Find() ([]*models.MeetingRoom, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MeetingRoom, err error)
	FindInBatches(result *[]*models.MeetingRoom, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.MeetingRoom) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMeetingRoomDo
	Assign(attrs ...field.AssignExpr) IMeetingRoomDo
	Joins(fields ...field.RelationField) IMeetingRoomDo
	Preload(fields ...field.RelationField) IMeetingRoomDo
	FirstOrInit() (*models.MeetingRoom, error)
	FirstOrCreate() (*models.MeetingRoom, error)
	FindByPage(offset int, limit int) (result []*models.MeetingRoom, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMeetingRoomDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m meetingRoomDo) Debug() IMeetingRoomDo {
	return m.withDO(m.DO.Debug())
}

func (m meetingRoomDo) WithContext(ctx context.Context) IMeetingRoomDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m meetingRoomDo) ReadDB() IMeetingRoomDo {
	return m.Clauses(dbresolver.Read)
}

func (m meetingRoomDo) WriteDB() IMeetingRoomDo {
	return m.Clauses(dbresolver.Write)
}

func (m meetingRoomDo) Session(config *gorm.Session) IMeetingRoomDo {
	return m.withDO(m.DO.Session(config))
}

func (m meetingRoomDo) Clauses(conds ...clause.Expression) IMeetingRoomDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m meetingRoomDo) Returning(value interface{}, columns ...string) IMeetingRoomDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m meetingRoomDo) Not(conds ...gen.Condition) IMeetingRoomDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m meetingRoomDo) Or(conds ...gen.Condition) IMeetingRoomDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m meetingRoomDo) Select(conds ...field.Expr) IMeetingRoomDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m meetingRoomDo) Where(conds ...gen.Condition) IMeetingRoomDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m meetingRoomDo) Order(conds ...field.Expr) IMeetingRoomDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m meetingRoomDo) Distinct(cols ...field.Expr) IMeetingRoomDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m meetingRoomDo) Omit(cols ...field.Expr) IMeetingRoomDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m meetingRoomDo) Join(table schema.Tabler, on ...field.Expr) IMeetingRoomDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m meetingRoomDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMeetingRoomDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m meetingRoomDo) RightJoin(table schema.Tabler, on ...field.Expr) IMeetingRoomDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m meetingRoomDo) Group(cols ...field.Expr) IMeetingRoomDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m meetingRoomDo) Having(conds ...gen.Condition) IMeetingRoomDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m meetingRoomDo) Limit(limit int) IMeetingRoomDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m meetingRoomDo) Offset(offset int) IMeetingRoomDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m meetingRoomDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMeetingRoomDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m meetingRoomDo) Unscoped() IMeetingRoomDo {
	return m.withDO(m.DO.Unscoped())
}

func (m meetingRoomDo) Create(values ...*models.MeetingRoom) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m meetingRoomDo) CreateInBatches(values []*models.MeetingRoom, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m meetingRoomDo) Save(values ...*models.MeetingRoom) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m meetingRoomDo) First() (*models.MeetingRoom, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingRoom), nil
	}
}

func (m meetingRoomDo) Take() (*models.MeetingRoom, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingRoom), nil
	}
}

func (m meetingRoomDo) Last() (*models.MeetingRoom, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingRoom), nil
	}
}

func (m meetingRoomDo) Find() ([]*models.MeetingRoom, error) {
	result, err := m.DO.Find()
	return result.([]*models.MeetingRoom), err
}

func (m meetingRoomDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MeetingRoom, err error) {
	buf := make([]*models.MeetingRoom, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m meetingRoomDo) FindInBatches(result *[]*models.MeetingRoom, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m meetingRoomDo) Attrs(attrs ...field.AssignExpr) IMeetingRoomDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m meetingRoomDo) Assign(attrs ...field.AssignExpr) IMeetingRoomDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m meetingRoomDo) Joins(fields ...field.RelationField) IMeetingRoomDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m meetingRoomDo) Preload(fields ...field.RelationField) IMeetingRoomDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m meetingRoomDo) FirstOrInit() (*models.MeetingRoom, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingRoom), nil
	}
}

func (m meetingRoomDo) FirstOrCreate() (*models.MeetingRoom, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingRoom), nil
	}
}

func (m meetingRoomDo) FindByPage(offset int, limit int) (result []*models.MeetingRoom, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m meetingRoomDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m meetingRoomDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m meetingRoomDo) Delete(models ...*models.MeetingRoom) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *meetingRoomDo) withDO(do gen.Dao) *meetingRoomDo {
	m.DO = *do.(*gen.DO)
	return m
}
