// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"fast-gin/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMeetingParticipant(db *gorm.DB, opts ...gen.DOOption) meetingParticipant {
	_meetingParticipant := meetingParticipant{}

	_meetingParticipant.meetingParticipantDo.UseDB(db, opts...)
	_meetingParticipant.meetingParticipantDo.UseModel(&models.MeetingParticipant{})

	tableName := _meetingParticipant.meetingParticipantDo.TableName()
	_meetingParticipant.ALL = field.NewAsterisk(tableName)
	_meetingParticipant.ID = field.NewUint(tableName, "id")
	_meetingParticipant.CreatedAt = field.NewTime(tableName, "created_at")
	_meetingParticipant.UpdatedAt = field.NewTime(tableName, "updated_at")
	_meetingParticipant.DeletedAt = field.NewField(tableName, "deleted_at")
	_meetingParticipant.MeetingID = field.NewUint(tableName, "meeting_id")
	_meetingParticipant.UserID = field.NewUint(tableName, "user_id")
	_meetingParticipant.DisplayName = field.NewString(tableName, "display_name")
	_meetingParticipant.JoinedAt = field.NewTime(tableName, "joined_at")
	_meetingParticipant.LeftAt = field.NewTime(tableName, "left_at")
	_meetingParticipant.IsHost = field.NewBool(tableName, "is_host")

	_meetingParticipant.fillFieldMap()

	return _meetingParticipant
}

type meetingParticipant struct {
	meetingParticipantDo meetingParticipantDo

	ALL         field.Asterisk
	ID          field.Uint   // 主键ID
	CreatedAt   field.Time   // 创建时间
	UpdatedAt   field.Time   // 更新时间
	DeletedAt   field.Field  // 删除时间
	MeetingID   field.Uint   // 会议ID
	UserID      field.Uint   // 用户ID
	DisplayName field.String // 参会显示名
	JoinedAt    field.Time   // 加入时间
	LeftAt      field.Time   // 离开时间
	IsHost      field.Bool   // 是否主持人

	fieldMap map[string]field.Expr
}

func (m meetingParticipant) Table(newTableName string) *meetingParticipant {
	m.meetingParticipantDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m meetingParticipant) As(alias string) *meetingParticipant {
	m.meetingParticipantDo.DO = *(m.meetingParticipantDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *meetingParticipant) updateTableName(table string) *meetingParticipant {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")
	m.MeetingID = field.NewUint(table, "meeting_id")
	m.UserID = field.NewUint(table, "user_id")
	m.DisplayName = field.NewString(table, "display_name")
	m.JoinedAt = field.NewTime(table, "joined_at")
	m.LeftAt = field.NewTime(table, "left_at")
	m.IsHost = field.NewBool(table, "is_host")

	m.fillFieldMap()

	return m
}

func (m *meetingParticipant) WithContext(ctx context.Context) IMeetingParticipantDo {
	return m.meetingParticipantDo.WithContext(ctx)
}

func (m meetingParticipant) TableName() string { return m.meetingParticipantDo.TableName() }

func (m meetingParticipant) Alias() string { return m.meetingParticipantDo.Alias() }

func (m meetingParticipant) Columns(cols ...field.Expr) gen.Columns {
	return m.meetingParticipantDo.Columns(cols...)
}

func (m *meetingParticipant) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *meetingParticipant) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 10)
	m.fieldMap["id"] = m.ID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
	m.fieldMap["meeting_id"] = m.MeetingID
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["display_name"] = m.DisplayName
	m.fieldMap["joined_at"] = m.JoinedAt
	m.fieldMap["left_at"] = m.LeftAt
	m.fieldMap["is_host"] = m.IsHost
}

func (m meetingParticipant) clone(db *gorm.DB) meetingParticipant {
	m.meetingParticipantDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m meetingParticipant) replaceDB(db *gorm.DB) meetingParticipant {
	m.meetingParticipantDo.ReplaceDB(db)
	return m
}

type meetingParticipantDo struct{ gen.DO }

type IMeetingParticipantDo interface {
	gen.SubQuery
	Debug() IMeetingParticipantDo
	WithContext(ctx context.Context) IMeetingParticipantDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMeetingParticipantDo
	WriteDB() IMeetingParticipantDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMeetingParticipantDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMeetingParticipantDo
	Not(conds ...gen.Condition) IMeetingParticipantDo
	Or(conds ...gen.Condition) IMeetingParticipantDo
	Select(conds ...field.Expr) IMeetingParticipantDo
	Where(conds ...gen.Condition) IMeetingParticipantDo
	Order(conds ...field.Expr) IMeetingParticipantDo
	Distinct(cols ...field.Expr) IMeetingParticipantDo
	Omit(cols ...field.Expr) IMeetingParticipantDo
	Join(table schema.Tabler, on ...field.Expr) IMeetingParticipantDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMeetingParticipantDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMeetingParticipantDo
	Group(cols ...field.Expr) IMeetingParticipantDo
	Having(conds ...gen.Condition) IMeetingParticipantDo
	Limit(limit int) IMeetingParticipantDo
	Offset(offset int) IMeetingParticipantDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMeetingParticipantDo
	Unscoped() IMeetingParticipantDo
	Create(values ...*models.MeetingParticipant) error
	CreateInBatches(values []*models.MeetingParticipant, batchSize int) error
	Save(values ...*models.MeetingParticipant) error
	First() (*models.MeetingParticipant, error)
	Take() (*models.MeetingParticipant, error)
	Last() (*models.MeetingParticipant, error)
	Find() ([]*models.MeetingParticipant, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MeetingParticipant, err error)
	FindInBatches(result *[]*models.MeetingParticipant, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.MeetingParticipant) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMeetingParticipantDo
	Assign(attrs ...field.AssignExpr) IMeetingParticipantDo
	Joins(fields ...field.RelationField) IMeetingParticipantDo
	Preload(fields ...field.RelationField) IMeetingParticipantDo
	FirstOrInit() (*models.MeetingParticipant, error)
	FirstOrCreate() (*models.MeetingParticipant, error)
	FindByPage(offset int, limit int) (result []*models.MeetingParticipant, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMeetingParticipantDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m meetingParticipantDo) Debug() IMeetingParticipantDo {
	return m.withDO(m.DO.Debug())
}

func (m meetingParticipantDo) WithContext(ctx context.Context) IMeetingParticipantDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m meetingParticipantDo) ReadDB() IMeetingParticipantDo {
	return m.Clauses(dbresolver.Read)
}

func (m meetingParticipantDo) WriteDB() IMeetingParticipantDo {
	return m.Clauses(dbresolver.Write)
}

func (m meetingParticipantDo) Session(config *gorm.Session) IMeetingParticipantDo {
	return m.withDO(m.DO.Session(config))
}

func (m meetingParticipantDo) Clauses(conds ...clause.Expression) IMeetingParticipantDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m meetingParticipantDo) Returning(value interface{}, columns ...string) IMeetingParticipantDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m meetingParticipantDo) Not(conds ...gen.Condition) IMeetingParticipantDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m meetingParticipantDo) Or(conds ...gen.Condition) IMeetingParticipantDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m meetingParticipantDo) Select(conds ...field.Expr) IMeetingParticipantDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m meetingParticipantDo) Where(conds ...gen.Condition) IMeetingParticipantDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m meetingParticipantDo) Order(conds ...field.Expr) IMeetingParticipantDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m meetingParticipantDo) Distinct(cols ...field.Expr) IMeetingParticipantDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m meetingParticipantDo) Omit(cols ...field.Expr) IMeetingParticipantDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m meetingParticipantDo) Join(table schema.Tabler, on ...field.Expr) IMeetingParticipantDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m meetingParticipantDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMeetingParticipantDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m meetingParticipantDo) RightJoin(table schema.Tabler, on ...field.Expr) IMeetingParticipantDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m meetingParticipantDo) Group(cols ...field.Expr) IMeetingParticipantDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m meetingParticipantDo) Having(conds ...gen.Condition) IMeetingParticipantDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m meetingParticipantDo) Limit(limit int) IMeetingParticipantDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m meetingParticipantDo) Offset(offset int) IMeetingParticipantDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m meetingParticipantDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMeetingParticipantDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m meetingParticipantDo) Unscoped() IMeetingParticipantDo {
	return m.withDO(m.DO.Unscoped())
}

func (m meetingParticipantDo) Create(values ...*models.MeetingParticipant) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m meetingParticipantDo) CreateInBatches(values []*models.MeetingParticipant, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m meetingParticipantDo) Save(values ...*models.MeetingParticipant) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m meetingParticipantDo) First() (*models.MeetingParticipant, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingParticipant), nil
	}
}

func (m meetingParticipantDo) Take() (*models.MeetingParticipant, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingParticipant), nil
	}
}

func (m meetingParticipantDo) Last() (*models.MeetingParticipant, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingParticipant), nil
	}
}

func (m meetingParticipantDo) Find() ([]*models.MeetingParticipant, error) {
	result, err := m.DO.Find()
	return result.([]*models.MeetingParticipant), err
}

func (m meetingParticipantDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MeetingParticipant, err error) {
	buf := make([]*models.MeetingParticipant, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m meetingParticipantDo) FindInBatches(result *[]*models.MeetingParticipant, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m meetingParticipantDo) Attrs(attrs ...field.AssignExpr) IMeetingParticipantDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m meetingParticipantDo) Assign(attrs ...field.AssignExpr) IMeetingParticipantDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m meetingParticipantDo) Joins(fields ...field.RelationField) IMeetingParticipantDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m meetingParticipantDo) Preload(fields ...field.RelationField) IMeetingParticipantDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m meetingParticipantDo) FirstOrInit() (*models.MeetingParticipant, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingParticipant), nil
	}
}

func (m meetingParticipantDo) FirstOrCreate() (*models.MeetingParticipant, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingParticipant), nil
	}
}

func (m meetingParticipantDo) FindByPage(offset int, limit int) (result []*models.MeetingParticipant, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m meetingParticipantDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m meetingParticipantDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m meetingParticipantDo) Delete(models ...*models.MeetingParticipant) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *meetingParticipantDo) withDO(do gen.Dao) *meetingParticipantDo {
	m.DO = *do.(*gen.DO)
	return m
}
