// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"fast-gin/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMeetingAttachment(db *gorm.DB, opts ...gen.DOOption) meetingAttachment {
	_meetingAttachment := meetingAttachment{}

	_meetingAttachment.meetingAttachmentDo.UseDB(db, opts...)
	_meetingAttachment.meetingAttachmentDo.UseModel(&models.MeetingAttachment{})

	tableName := _meetingAttachment.meetingAttachmentDo.TableName()
	_meetingAttachment.ALL = field.NewAsterisk(tableName)
	_meetingAttachment.ID = field.NewUint(tableName, "id")
	_meetingAttachment.CreatedAt = field.NewTime(tableName, "created_at")
	_meetingAttachment.UpdatedAt = field.NewTime(tableName, "updated_at")
	_meetingAttachment.DeletedAt = field.NewField(tableName, "deleted_at")
	_meetingAttachment.RoomID = field.NewUint(tableName, "room_id")
	_meetingAttachment.UploaderID = field.NewUint(tableName, "uploader_id")
	_meetingAttachment.FileID = field.NewUint(tableName, "file_id")
	_meetingAttachment.Title = field.NewString(tableName, "title")
	_meetingAttachment.FileType = field.NewString(tableName, "file_type")

	_meetingAttachment.fillFieldMap()

	return _meetingAttachment
}

type meetingAttachment struct {
	meetingAttachmentDo meetingAttachmentDo

	ALL        field.Asterisk
	ID         field.Uint   // 主键ID
	CreatedAt  field.Time   // 创建时间
	UpdatedAt  field.Time   // 更新时间
	DeletedAt  field.Field  // 删除时间
	RoomID     field.Uint   // 会议ID
	UploaderID field.Uint   // 上传者ID
	FileID     field.Uint   // 文件ID
	Title      field.String // 附件标题
	FileType   field.String // 文件类型

	fieldMap map[string]field.Expr
}

func (m meetingAttachment) Table(newTableName string) *meetingAttachment {
	m.meetingAttachmentDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m meetingAttachment) As(alias string) *meetingAttachment {
	m.meetingAttachmentDo.DO = *(m.meetingAttachmentDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *meetingAttachment) updateTableName(table string) *meetingAttachment {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")
	m.RoomID = field.NewUint(table, "room_id")
	m.UploaderID = field.NewUint(table, "uploader_id")
	m.FileID = field.NewUint(table, "file_id")
	m.Title = field.NewString(table, "title")
	m.FileType = field.NewString(table, "file_type")

	m.fillFieldMap()

	return m
}

func (m *meetingAttachment) WithContext(ctx context.Context) IMeetingAttachmentDo {
	return m.meetingAttachmentDo.WithContext(ctx)
}

func (m meetingAttachment) TableName() string { return m.meetingAttachmentDo.TableName() }

func (m meetingAttachment) Alias() string { return m.meetingAttachmentDo.Alias() }

func (m meetingAttachment) Columns(cols ...field.Expr) gen.Columns {
	return m.meetingAttachmentDo.Columns(cols...)
}

func (m *meetingAttachment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *meetingAttachment) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 9)
	m.fieldMap["id"] = m.ID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
	m.fieldMap["room_id"] = m.RoomID
	m.fieldMap["uploader_id"] = m.UploaderID
	m.fieldMap["file_id"] = m.FileID
	m.fieldMap["title"] = m.Title
	m.fieldMap["file_type"] = m.FileType
}

func (m meetingAttachment) clone(db *gorm.DB) meetingAttachment {
	m.meetingAttachmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m meetingAttachment) replaceDB(db *gorm.DB) meetingAttachment {
	m.meetingAttachmentDo.ReplaceDB(db)
	return m
}

type meetingAttachmentDo struct{ gen.DO }

type IMeetingAttachmentDo interface {
	gen.SubQuery
	Debug() IMeetingAttachmentDo
	WithContext(ctx context.Context) IMeetingAttachmentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMeetingAttachmentDo
	WriteDB() IMeetingAttachmentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMeetingAttachmentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMeetingAttachmentDo
	Not(conds ...gen.Condition) IMeetingAttachmentDo
	Or(conds ...gen.Condition) IMeetingAttachmentDo
	Select(conds ...field.Expr) IMeetingAttachmentDo
	Where(conds ...gen.Condition) IMeetingAttachmentDo
	Order(conds ...field.Expr) IMeetingAttachmentDo
	Distinct(cols ...field.Expr) IMeetingAttachmentDo
	Omit(cols ...field.Expr) IMeetingAttachmentDo
	Join(table schema.Tabler, on ...field.Expr) IMeetingAttachmentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMeetingAttachmentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMeetingAttachmentDo
	Group(cols ...field.Expr) IMeetingAttachmentDo
	Having(conds ...gen.Condition) IMeetingAttachmentDo
	Limit(limit int) IMeetingAttachmentDo
	Offset(offset int) IMeetingAttachmentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMeetingAttachmentDo
	Unscoped() IMeetingAttachmentDo
	Create(values ...*models.MeetingAttachment) error
	CreateInBatches(values []*models.MeetingAttachment, batchSize int) error
	Save(values ...*models.MeetingAttachment) error
	First() (*models.MeetingAttachment, error)
	Take() (*models.MeetingAttachment, error)
	Last() (*models.MeetingAttachment, error)
	Find() ([]*models.MeetingAttachment, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MeetingAttachment, err error)
	FindInBatches(result *[]*models.MeetingAttachment, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.MeetingAttachment) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMeetingAttachmentDo
	Assign(attrs ...field.AssignExpr) IMeetingAttachmentDo
	Joins(fields ...field.RelationField) IMeetingAttachmentDo
	Preload(fields ...field.RelationField) IMeetingAttachmentDo
	FirstOrInit() (*models.MeetingAttachment, error)
	FirstOrCreate() (*models.MeetingAttachment, error)
	FindByPage(offset int, limit int) (result []*models.MeetingAttachment, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMeetingAttachmentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m meetingAttachmentDo) Debug() IMeetingAttachmentDo {
	return m.withDO(m.DO.Debug())
}

func (m meetingAttachmentDo) WithContext(ctx context.Context) IMeetingAttachmentDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m meetingAttachmentDo) ReadDB() IMeetingAttachmentDo {
	return m.Clauses(dbresolver.Read)
}

func (m meetingAttachmentDo) WriteDB() IMeetingAttachmentDo {
	return m.Clauses(dbresolver.Write)
}

func (m meetingAttachmentDo) Session(config *gorm.Session) IMeetingAttachmentDo {
	return m.withDO(m.DO.Session(config))
}

func (m meetingAttachmentDo) Clauses(conds ...clause.Expression) IMeetingAttachmentDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m meetingAttachmentDo) Returning(value interface{}, columns ...string) IMeetingAttachmentDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m meetingAttachmentDo) Not(conds ...gen.Condition) IMeetingAttachmentDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m meetingAttachmentDo) Or(conds ...gen.Condition) IMeetingAttachmentDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m meetingAttachmentDo) Select(conds ...field.Expr) IMeetingAttachmentDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m meetingAttachmentDo) Where(conds ...gen.Condition) IMeetingAttachmentDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m meetingAttachmentDo) Order(conds ...field.Expr) IMeetingAttachmentDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m meetingAttachmentDo) Distinct(cols ...field.Expr) IMeetingAttachmentDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m meetingAttachmentDo) Omit(cols ...field.Expr) IMeetingAttachmentDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m meetingAttachmentDo) Join(table schema.Tabler, on ...field.Expr) IMeetingAttachmentDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m meetingAttachmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMeetingAttachmentDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m meetingAttachmentDo) RightJoin(table schema.Tabler, on ...field.Expr) IMeetingAttachmentDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m meetingAttachmentDo) Group(cols ...field.Expr) IMeetingAttachmentDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m meetingAttachmentDo) Having(conds ...gen.Condition) IMeetingAttachmentDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m meetingAttachmentDo) Limit(limit int) IMeetingAttachmentDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m meetingAttachmentDo) Offset(offset int) IMeetingAttachmentDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m meetingAttachmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMeetingAttachmentDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m meetingAttachmentDo) Unscoped() IMeetingAttachmentDo {
	return m.withDO(m.DO.Unscoped())
}

func (m meetingAttachmentDo) Create(values ...*models.MeetingAttachment) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m meetingAttachmentDo) CreateInBatches(values []*models.MeetingAttachment, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m meetingAttachmentDo) Save(values ...*models.MeetingAttachment) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m meetingAttachmentDo) First() (*models.MeetingAttachment, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingAttachment), nil
	}
}

func (m meetingAttachmentDo) Take() (*models.MeetingAttachment, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingAttachment), nil
	}
}

func (m meetingAttachmentDo) Last() (*models.MeetingAttachment, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingAttachment), nil
	}
}

func (m meetingAttachmentDo) Find() ([]*models.MeetingAttachment, error) {
	result, err := m.DO.Find()
	return result.([]*models.MeetingAttachment), err
}

func (m meetingAttachmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MeetingAttachment, err error) {
	buf := make([]*models.MeetingAttachment, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m meetingAttachmentDo) FindInBatches(result *[]*models.MeetingAttachment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m meetingAttachmentDo) Attrs(attrs ...field.AssignExpr) IMeetingAttachmentDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m meetingAttachmentDo) Assign(attrs ...field.AssignExpr) IMeetingAttachmentDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m meetingAttachmentDo) Joins(fields ...field.RelationField) IMeetingAttachmentDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m meetingAttachmentDo) Preload(fields ...field.RelationField) IMeetingAttachmentDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m meetingAttachmentDo) FirstOrInit() (*models.MeetingAttachment, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingAttachment), nil
	}
}

func (m meetingAttachmentDo) FirstOrCreate() (*models.MeetingAttachment, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingAttachment), nil
	}
}

func (m meetingAttachmentDo) FindByPage(offset int, limit int) (result []*models.MeetingAttachment, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m meetingAttachmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m meetingAttachmentDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m meetingAttachmentDo) Delete(models ...*models.MeetingAttachment) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *meetingAttachmentDo) withDO(do gen.Dao) *meetingAttachmentDo {
	m.DO = *do.(*gen.DO)
	return m
}
