// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"fast-gin/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMeetingRoomMember(db *gorm.DB, opts ...gen.DOOption) meetingRoomMember {
	_meetingRoomMember := meetingRoomMember{}

	_meetingRoomMember.meetingRoomMemberDo.UseDB(db, opts...)
	_meetingRoomMember.meetingRoomMemberDo.UseModel(&models.MeetingRoomMember{})

	tableName := _meetingRoomMember.meetingRoomMemberDo.TableName()
	_meetingRoomMember.ALL = field.NewAsterisk(tableName)
	_meetingRoomMember.ID = field.NewUint(tableName, "id")
	_meetingRoomMember.CreatedAt = field.NewTime(tableName, "created_at")
	_meetingRoomMember.UpdatedAt = field.NewTime(tableName, "updated_at")
	_meetingRoomMember.DeletedAt = field.NewField(tableName, "deleted_at")
	_meetingRoomMember.RoomID = field.NewUint(tableName, "room_id")
	_meetingRoomMember.UserID = field.NewUint(tableName, "user_id")
	_meetingRoomMember.MemberStatus = field.NewInt8(tableName, "member_status")
	_meetingRoomMember.JoinTime = field.NewInt64(tableName, "join_time")
	_meetingRoomMember.LeaveTime = field.NewInt64(tableName, "leave_time")

	_meetingRoomMember.fillFieldMap()

	return _meetingRoomMember
}

type meetingRoomMember struct {
	meetingRoomMemberDo meetingRoomMemberDo

	ALL          field.Asterisk
	ID           field.Uint  // 主键ID
	CreatedAt    field.Time  // 创建时间
	UpdatedAt    field.Time  // 更新时间
	DeletedAt    field.Field // 删除时间
	RoomID       field.Uint  // 会议ID
	UserID       field.Uint  // 用户ID
	MemberStatus field.Int8  // 成员状态 0在会 1已离开
	JoinTime     field.Int64 // 加入时间戳
	LeaveTime    field.Int64 // 离开时间戳

	fieldMap map[string]field.Expr
}

func (m meetingRoomMember) Table(newTableName string) *meetingRoomMember {
	m.meetingRoomMemberDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m meetingRoomMember) As(alias string) *meetingRoomMember {
	m.meetingRoomMemberDo.DO = *(m.meetingRoomMemberDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *meetingRoomMember) updateTableName(table string) *meetingRoomMember {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")
	m.RoomID = field.NewUint(table, "room_id")
	m.UserID = field.NewUint(table, "user_id")
	m.MemberStatus = field.NewInt8(table, "member_status")
	m.JoinTime = field.NewInt64(table, "join_time")
	m.LeaveTime = field.NewInt64(table, "leave_time")

	m.fillFieldMap()

	return m
}

func (m *meetingRoomMember) WithContext(ctx context.Context) IMeetingRoomMemberDo {
	return m.meetingRoomMemberDo.WithContext(ctx)
}

func (m meetingRoomMember) TableName() string { return m.meetingRoomMemberDo.TableName() }

func (m meetingRoomMember) Alias() string { return m.meetingRoomMemberDo.Alias() }

func (m meetingRoomMember) Columns(cols ...field.Expr) gen.Columns {
	return m.meetingRoomMemberDo.Columns(cols...)
}

func (m *meetingRoomMember) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *meetingRoomMember) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 9)
	m.fieldMap["id"] = m.ID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
	m.fieldMap["room_id"] = m.RoomID
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["member_status"] = m.MemberStatus
	m.fieldMap["join_time"] = m.JoinTime
	m.fieldMap["leave_time"] = m.LeaveTime
}

func (m meetingRoomMember) clone(db *gorm.DB) meetingRoomMember {
	m.meetingRoomMemberDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m meetingRoomMember) replaceDB(db *gorm.DB) meetingRoomMember {
	m.meetingRoomMemberDo.ReplaceDB(db)
	return m
}

type meetingRoomMemberDo struct{ gen.DO }

type IMeetingRoomMemberDo interface {
	gen.SubQuery
	Debug() IMeetingRoomMemberDo
	WithContext(ctx context.Context) IMeetingRoomMemberDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMeetingRoomMemberDo
	WriteDB() IMeetingRoomMemberDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMeetingRoomMemberDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMeetingRoomMemberDo
	Not(conds ...gen.Condition) IMeetingRoomMemberDo
	Or(conds ...gen.Condition) IMeetingRoomMemberDo
	Select(conds ...field.Expr) IMeetingRoomMemberDo
	Where(conds ...gen.Condition) IMeetingRoomMemberDo
	Order(conds ...field.Expr) IMeetingRoomMemberDo
	Distinct(cols ...field.Expr) IMeetingRoomMemberDo
	Omit(cols ...field.Expr) IMeetingRoomMemberDo
	Join(table schema.Tabler, on ...field.Expr) IMeetingRoomMemberDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMeetingRoomMemberDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMeetingRoomMemberDo
	Group(cols ...field.Expr) IMeetingRoomMemberDo
	Having(conds ...gen.Condition) IMeetingRoomMemberDo
	Limit(limit int) IMeetingRoomMemberDo
	Offset(offset int) IMeetingRoomMemberDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMeetingRoomMemberDo
	Unscoped() IMeetingRoomMemberDo
	Create(values ...*models.MeetingRoomMember) error
	CreateInBatches(values []*models.MeetingRoomMember, batchSize int) error
	Save(values ...*models.MeetingRoomMember) error
	First() (*models.MeetingRoomMember, error)
	Take() (*models.MeetingRoomMember, error)
	Last() (*models.MeetingRoomMember, error)
	Find() ([]*models.MeetingRoomMember, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MeetingRoomMember, err error)
	FindInBatches(result *[]*models.MeetingRoomMember, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.MeetingRoomMember) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMeetingRoomMemberDo
	Assign(attrs ...field.AssignExpr) IMeetingRoomMemberDo
	Joins(fields ...field.RelationField) IMeetingRoomMemberDo
	Preload(fields ...field.RelationField) IMeetingRoomMemberDo
	FirstOrInit() (*models.MeetingRoomMember, error)
	FirstOrCreate() (*models.MeetingRoomMember, error)
	FindByPage(offset int, limit int) (result []*models.MeetingRoomMember, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMeetingRoomMemberDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m meetingRoomMemberDo) Debug() IMeetingRoomMemberDo {
	return m.withDO(m.DO.Debug())
}

func (m meetingRoomMemberDo) WithContext(ctx context.Context) IMeetingRoomMemberDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m meetingRoomMemberDo) ReadDB() IMeetingRoomMemberDo {
	return m.Clauses(dbresolver.Read)
}

func (m meetingRoomMemberDo) WriteDB() IMeetingRoomMemberDo {
	return m.Clauses(dbresolver.Write)
}

func (m meetingRoomMemberDo) Session(config *gorm.Session) IMeetingRoomMemberDo {
	return m.withDO(m.DO.Session(config))
}

func (m meetingRoomMemberDo) Clauses(conds ...clause.Expression) IMeetingRoomMemberDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m meetingRoomMemberDo) Returning(value interface{}, columns ...string) IMeetingRoomMemberDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m meetingRoomMemberDo) Not(conds ...gen.Condition) IMeetingRoomMemberDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m meetingRoomMemberDo) Or(conds ...gen.Condition) IMeetingRoomMemberDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m meetingRoomMemberDo) Select(conds ...field.Expr) IMeetingRoomMemberDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m meetingRoomMemberDo) Where(conds ...gen.Condition) IMeetingRoomMemberDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m meetingRoomMemberDo) Order(conds ...field.Expr) IMeetingRoomMemberDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m meetingRoomMemberDo) Distinct(cols ...field.Expr) IMeetingRoomMemberDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m meetingRoomMemberDo) Omit(cols ...field.Expr) IMeetingRoomMemberDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m meetingRoomMemberDo) Join(table schema.Tabler, on ...field.Expr) IMeetingRoomMemberDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m meetingRoomMemberDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMeetingRoomMemberDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m meetingRoomMemberDo) RightJoin(table schema.Tabler, on ...field.Expr) IMeetingRoomMemberDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m meetingRoomMemberDo) Group(cols ...field.Expr) IMeetingRoomMemberDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m meetingRoomMemberDo) Having(conds ...gen.Condition) IMeetingRoomMemberDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m meetingRoomMemberDo) Limit(limit int) IMeetingRoomMemberDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m meetingRoomMemberDo) Offset(offset int) IMeetingRoomMemberDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m meetingRoomMemberDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMeetingRoomMemberDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m meetingRoomMemberDo) Unscoped() IMeetingRoomMemberDo {
	return m.withDO(m.DO.Unscoped())
}

func (m meetingRoomMemberDo) Create(values ...*models.MeetingRoomMember) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m meetingRoomMemberDo) CreateInBatches(values []*models.MeetingRoomMember, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m meetingRoomMemberDo) Save(values ...*models.MeetingRoomMember) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m meetingRoomMemberDo) First() (*models.MeetingRoomMember, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingRoomMember), nil
	}
}

func (m meetingRoomMemberDo) Take() (*models.MeetingRoomMember, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingRoomMember), nil
	}
}

func (m meetingRoomMemberDo) Last() (*models.MeetingRoomMember, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingRoomMember), nil
	}
}

func (m meetingRoomMemberDo) Find() ([]*models.MeetingRoomMember, error) {
	result, err := m.DO.Find()
	return result.([]*models.MeetingRoomMember), err
}

func (m meetingRoomMemberDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MeetingRoomMember, err error) {
	buf := make([]*models.MeetingRoomMember, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m meetingRoomMemberDo) FindInBatches(result *[]*models.MeetingRoomMember, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m meetingRoomMemberDo) Attrs(attrs ...field.AssignExpr) IMeetingRoomMemberDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m meetingRoomMemberDo) Assign(attrs ...field.AssignExpr) IMeetingRoomMemberDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m meetingRoomMemberDo) Joins(fields ...field.RelationField) IMeetingRoomMemberDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m meetingRoomMemberDo) Preload(fields ...field.RelationField) IMeetingRoomMemberDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m meetingRoomMemberDo) FirstOrInit() (*models.MeetingRoomMember, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingRoomMember), nil
	}
}

func (m meetingRoomMemberDo) FirstOrCreate() (*models.MeetingRoomMember, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingRoomMember), nil
	}
}

func (m meetingRoomMemberDo) FindByPage(offset int, limit int) (result []*models.MeetingRoomMember, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m meetingRoomMemberDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m meetingRoomMemberDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m meetingRoomMemberDo) Delete(models ...*models.MeetingRoomMember) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *meetingRoomMemberDo) withDO(do gen.Dao) *meetingRoomMemberDo {
	m.DO = *do.(*gen.DO)
	return m
}
