// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"fast-gin/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMeetingQualitySnapshot(db *gorm.DB, opts ...gen.DOOption) meetingQualitySnapshot {
	_meetingQualitySnapshot := meetingQualitySnapshot{}

	_meetingQualitySnapshot.meetingQualitySnapshotDo.UseDB(db, opts...)
	_meetingQualitySnapshot.meetingQualitySnapshotDo.UseModel(&models.MeetingQualitySnapshot{})

	tableName := _meetingQualitySnapshot.meetingQualitySnapshotDo.TableName()
	_meetingQualitySnapshot.ALL = field.NewAsterisk(tableName)
	_meetingQualitySnapshot.ID = field.NewUint(tableName, "id")
	_meetingQualitySnapshot.CreatedAt = field.NewTime(tableName, "created_at")
	_meetingQualitySnapshot.UpdatedAt = field.NewTime(tableName, "updated_at")
	_meetingQualitySnapshot.DeletedAt = field.NewField(tableName, "deleted_at")
	_meetingQualitySnapshot.MeetingID = field.NewUint(tableName, "meeting_id")
	_meetingQualitySnapshot.UserID = field.NewUint(tableName, "user_id")
	_meetingQualitySnapshot.ClientID = field.NewString(tableName, "client_id")
	_meetingQualitySnapshot.Label = field.NewString(tableName, "label")
	_meetingQualitySnapshot.BytesSent = field.NewInt64(tableName, "bytes_sent")
	_meetingQualitySnapshot.BytesReceived = field.NewInt64(tableName, "bytes_received")
	_meetingQualitySnapshot.PacketsSent = field.NewInt64(tableName, "packets_sent")
	_meetingQualitySnapshot.PacketsReceived = field.NewInt64(tableName, "packets_received")
	_meetingQualitySnapshot.PacketsLost = field.NewInt64(tableName, "packets_lost")
	_meetingQualitySnapshot.JitterMs = field.NewFloat64(tableName, "jitter_ms")
	_meetingQualitySnapshot.RoundTripMs = field.NewFloat64(tableName, "round_trip_ms")
	_meetingQualitySnapshot.BitrateKbps = field.NewFloat64(tableName, "bitrate_kbps")
	_meetingQualitySnapshot.FrameWidth = field.NewInt(tableName, "frame_width")
	_meetingQualitySnapshot.FrameHeight = field.NewInt(tableName, "frame_height")
	_meetingQualitySnapshot.FPS = field.NewFloat64(tableName, "fps")
	_meetingQualitySnapshot.FramesDecoded = field.NewInt(tableName, "frames_decoded")
	_meetingQualitySnapshot.TotalFramesLost = field.NewInt(tableName, "total_frames_lost")
	_meetingQualitySnapshot.CandidateType = field.NewString(tableName, "candidate_type")
	_meetingQualitySnapshot.SnapshotAt = field.NewTime(tableName, "snapshot_at")

	_meetingQualitySnapshot.fillFieldMap()

	return _meetingQualitySnapshot
}

type meetingQualitySnapshot struct {
	meetingQualitySnapshotDo meetingQualitySnapshotDo

	ALL             field.Asterisk
	ID              field.Uint    // 主键ID
	CreatedAt       field.Time    // 创建时间
	UpdatedAt       field.Time    // 更新时间
	DeletedAt       field.Field   // 删除时间
	MeetingID       field.Uint    // 会议ID
	UserID          field.Uint    // 用户ID
	ClientID        field.String  // 客户端ID
	Label           field.String  // 标签(audio/video/connection)
	BytesSent       field.Int64   // 累计发送字节数
	BytesReceived   field.Int64   // 累计接收字节数
	PacketsSent     field.Int64   // 累计发送包数
	PacketsReceived field.Int64   // 累计接收包数
	PacketsLost     field.Int64   // 累计丢包数
	JitterMs        field.Float64 // 抖动(ms)
	RoundTripMs     field.Float64 // 往返时延(ms)
	BitrateKbps     field.Float64 // 估算比特率(kbps)
	FrameWidth      field.Int     // 视频宽度
	FrameHeight     field.Int     // 视频高度
	FPS             field.Float64 // 帧率
	FramesDecoded   field.Int     // 已解码帧数
	TotalFramesLost field.Int     // 总丢失帧数
	CandidateType   field.String  // ICE候选类型(host/srflx/relay)
	SnapshotAt      field.Time    // 采集时间

	fieldMap map[string]field.Expr
}

func (m meetingQualitySnapshot) Table(newTableName string) *meetingQualitySnapshot {
	m.meetingQualitySnapshotDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m meetingQualitySnapshot) As(alias string) *meetingQualitySnapshot {
	m.meetingQualitySnapshotDo.DO = *(m.meetingQualitySnapshotDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *meetingQualitySnapshot) updateTableName(table string) *meetingQualitySnapshot {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")
	m.MeetingID = field.NewUint(table, "meeting_id")
	m.UserID = field.NewUint(table, "user_id")
	m.ClientID = field.NewString(table, "client_id")
	m.Label = field.NewString(table, "label")
	m.BytesSent = field.NewInt64(table, "bytes_sent")
	m.BytesReceived = field.NewInt64(table, "bytes_received")
	m.PacketsSent = field.NewInt64(table, "packets_sent")
	m.PacketsReceived = field.NewInt64(table, "packets_received")
	m.PacketsLost = field.NewInt64(table, "packets_lost")
	m.JitterMs = field.NewFloat64(table, "jitter_ms")
	m.RoundTripMs = field.NewFloat64(table, "round_trip_ms")
	m.BitrateKbps = field.NewFloat64(table, "bitrate_kbps")
	m.FrameWidth = field.NewInt(table, "frame_width")
	m.FrameHeight = field.NewInt(table, "frame_height")
	m.FPS = field.NewFloat64(table, "fps")
	m.FramesDecoded = field.NewInt(table, "frames_decoded")
	m.TotalFramesLost = field.NewInt(table, "total_frames_lost")
	m.CandidateType = field.NewString(table, "candidate_type")
	m.SnapshotAt = field.NewTime(table, "snapshot_at")

	m.fillFieldMap()

	return m
}

func (m *meetingQualitySnapshot) WithContext(ctx context.Context) IMeetingQualitySnapshotDo {
	return m.meetingQualitySnapshotDo.WithContext(ctx)
}

func (m meetingQualitySnapshot) TableName() string { return m.meetingQualitySnapshotDo.TableName() }

func (m meetingQualitySnapshot) Alias() string { return m.meetingQualitySnapshotDo.Alias() }

func (m meetingQualitySnapshot) Columns(cols ...field.Expr) gen.Columns {
	return m.meetingQualitySnapshotDo.Columns(cols...)
}

func (m *meetingQualitySnapshot) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *meetingQualitySnapshot) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 23)
	m.fieldMap["id"] = m.ID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
	m.fieldMap["meeting_id"] = m.MeetingID
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["client_id"] = m.ClientID
	m.fieldMap["label"] = m.Label
	m.fieldMap["bytes_sent"] = m.BytesSent
	m.fieldMap["bytes_received"] = m.BytesReceived
	m.fieldMap["packets_sent"] = m.PacketsSent
	m.fieldMap["packets_received"] = m.PacketsReceived
	m.fieldMap["packets_lost"] = m.PacketsLost
	m.fieldMap["jitter_ms"] = m.JitterMs
	m.fieldMap["round_trip_ms"] = m.RoundTripMs
	m.fieldMap["bitrate_kbps"] = m.BitrateKbps
	m.fieldMap["frame_width"] = m.FrameWidth
	m.fieldMap["frame_height"] = m.FrameHeight
	m.fieldMap["fps"] = m.FPS
	m.fieldMap["frames_decoded"] = m.FramesDecoded
	m.fieldMap["total_frames_lost"] = m.TotalFramesLost
	m.fieldMap["candidate_type"] = m.CandidateType
	m.fieldMap["snapshot_at"] = m.SnapshotAt
}

func (m meetingQualitySnapshot) clone(db *gorm.DB) meetingQualitySnapshot {
	m.meetingQualitySnapshotDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m meetingQualitySnapshot) replaceDB(db *gorm.DB) meetingQualitySnapshot {
	m.meetingQualitySnapshotDo.ReplaceDB(db)
	return m
}

type meetingQualitySnapshotDo struct{ gen.DO }

type IMeetingQualitySnapshotDo interface {
	gen.SubQuery
	Debug() IMeetingQualitySnapshotDo
	WithContext(ctx context.Context) IMeetingQualitySnapshotDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMeetingQualitySnapshotDo
	WriteDB() IMeetingQualitySnapshotDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMeetingQualitySnapshotDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMeetingQualitySnapshotDo
	Not(conds ...gen.Condition) IMeetingQualitySnapshotDo
	Or(conds ...gen.Condition) IMeetingQualitySnapshotDo
	Select(conds ...field.Expr) IMeetingQualitySnapshotDo
	Where(conds ...gen.Condition) IMeetingQualitySnapshotDo
	Order(conds ...field.Expr) IMeetingQualitySnapshotDo
	Distinct(cols ...field.Expr) IMeetingQualitySnapshotDo
	Omit(cols ...field.Expr) IMeetingQualitySnapshotDo
	Join(table schema.Tabler, on ...field.Expr) IMeetingQualitySnapshotDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMeetingQualitySnapshotDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMeetingQualitySnapshotDo
	Group(cols ...field.Expr) IMeetingQualitySnapshotDo
	Having(conds ...gen.Condition) IMeetingQualitySnapshotDo
	Limit(limit int) IMeetingQualitySnapshotDo
	Offset(offset int) IMeetingQualitySnapshotDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMeetingQualitySnapshotDo
	Unscoped() IMeetingQualitySnapshotDo
	Create(values ...*models.MeetingQualitySnapshot) error
	CreateInBatches(values []*models.MeetingQualitySnapshot, batchSize int) error
	Save(values ...*models.MeetingQualitySnapshot) error
	First() (*models.MeetingQualitySnapshot, error)
	Take() (*models.MeetingQualitySnapshot, error)
	Last() (*models.MeetingQualitySnapshot, error)
	Find() ([]*models.MeetingQualitySnapshot, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MeetingQualitySnapshot, err error)
	FindInBatches(result *[]*models.MeetingQualitySnapshot, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.MeetingQualitySnapshot) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMeetingQualitySnapshotDo
	Assign(attrs ...field.AssignExpr) IMeetingQualitySnapshotDo
	Joins(fields ...field.RelationField) IMeetingQualitySnapshotDo
	Preload(fields ...field.RelationField) IMeetingQualitySnapshotDo
	FirstOrInit() (*models.MeetingQualitySnapshot, error)
	FirstOrCreate() (*models.MeetingQualitySnapshot, error)
	FindByPage(offset int, limit int) (result []*models.MeetingQualitySnapshot, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMeetingQualitySnapshotDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m meetingQualitySnapshotDo) Debug() IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Debug())
}

func (m meetingQualitySnapshotDo) WithContext(ctx context.Context) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m meetingQualitySnapshotDo) ReadDB() IMeetingQualitySnapshotDo {
	return m.Clauses(dbresolver.Read)
}

func (m meetingQualitySnapshotDo) WriteDB() IMeetingQualitySnapshotDo {
	return m.Clauses(dbresolver.Write)
}

func (m meetingQualitySnapshotDo) Session(config *gorm.Session) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Session(config))
}

func (m meetingQualitySnapshotDo) Clauses(conds ...clause.Expression) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m meetingQualitySnapshotDo) Returning(value interface{}, columns ...string) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m meetingQualitySnapshotDo) Not(conds ...gen.Condition) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m meetingQualitySnapshotDo) Or(conds ...gen.Condition) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m meetingQualitySnapshotDo) Select(conds ...field.Expr) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m meetingQualitySnapshotDo) Where(conds ...gen.Condition) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m meetingQualitySnapshotDo) Order(conds ...field.Expr) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m meetingQualitySnapshotDo) Distinct(cols ...field.Expr) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m meetingQualitySnapshotDo) Omit(cols ...field.Expr) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m meetingQualitySnapshotDo) Join(table schema.Tabler, on ...field.Expr) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m meetingQualitySnapshotDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m meetingQualitySnapshotDo) RightJoin(table schema.Tabler, on ...field.Expr) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m meetingQualitySnapshotDo) Group(cols ...field.Expr) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m meetingQualitySnapshotDo) Having(conds ...gen.Condition) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m meetingQualitySnapshotDo) Limit(limit int) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m meetingQualitySnapshotDo) Offset(offset int) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m meetingQualitySnapshotDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m meetingQualitySnapshotDo) Unscoped() IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Unscoped())
}

func (m meetingQualitySnapshotDo) Create(values ...*models.MeetingQualitySnapshot) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m meetingQualitySnapshotDo) CreateInBatches(values []*models.MeetingQualitySnapshot, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m meetingQualitySnapshotDo) Save(values ...*models.MeetingQualitySnapshot) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m meetingQualitySnapshotDo) First() (*models.MeetingQualitySnapshot, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingQualitySnapshot), nil
	}
}

func (m meetingQualitySnapshotDo) Take() (*models.MeetingQualitySnapshot, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingQualitySnapshot), nil
	}
}

func (m meetingQualitySnapshotDo) Last() (*models.MeetingQualitySnapshot, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingQualitySnapshot), nil
	}
}

func (m meetingQualitySnapshotDo) Find() ([]*models.MeetingQualitySnapshot, error) {
	result, err := m.DO.Find()
	return result.([]*models.MeetingQualitySnapshot), err
}

func (m meetingQualitySnapshotDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MeetingQualitySnapshot, err error) {
	buf := make([]*models.MeetingQualitySnapshot, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m meetingQualitySnapshotDo) FindInBatches(result *[]*models.MeetingQualitySnapshot, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m meetingQualitySnapshotDo) Attrs(attrs ...field.AssignExpr) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m meetingQualitySnapshotDo) Assign(attrs ...field.AssignExpr) IMeetingQualitySnapshotDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m meetingQualitySnapshotDo) Joins(fields ...field.RelationField) IMeetingQualitySnapshotDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m meetingQualitySnapshotDo) Preload(fields ...field.RelationField) IMeetingQualitySnapshotDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m meetingQualitySnapshotDo) FirstOrInit() (*models.MeetingQualitySnapshot, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingQualitySnapshot), nil
	}
}

func (m meetingQualitySnapshotDo) FirstOrCreate() (*models.MeetingQualitySnapshot, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingQualitySnapshot), nil
	}
}

func (m meetingQualitySnapshotDo) FindByPage(offset int, limit int) (result []*models.MeetingQualitySnapshot, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m meetingQualitySnapshotDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m meetingQualitySnapshotDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m meetingQualitySnapshotDo) Delete(models ...*models.MeetingQualitySnapshot) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *meetingQualitySnapshotDo) withDO(do gen.Dao) *meetingQualitySnapshotDo {
	m.DO = *do.(*gen.DO)
	return m
}
