// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"fast-gin/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMeetingActionLog(db *gorm.DB, opts ...gen.DOOption) meetingActionLog {
	_meetingActionLog := meetingActionLog{}

	_meetingActionLog.meetingActionLogDo.UseDB(db, opts...)
	_meetingActionLog.meetingActionLogDo.UseModel(&models.MeetingActionLog{})

	tableName := _meetingActionLog.meetingActionLogDo.TableName()
	_meetingActionLog.ALL = field.NewAsterisk(tableName)
	_meetingActionLog.ID = field.NewUint(tableName, "id")
	_meetingActionLog.CreatedAt = field.NewTime(tableName, "created_at")
	_meetingActionLog.UpdatedAt = field.NewTime(tableName, "updated_at")
	_meetingActionLog.DeletedAt = field.NewField(tableName, "deleted_at")
	_meetingActionLog.RoomID = field.NewUint(tableName, "room_id")
	_meetingActionLog.UserID = field.NewUint(tableName, "user_id")
	_meetingActionLog.Action = field.NewString(tableName, "action")
	_meetingActionLog.Detail = field.NewString(tableName, "detail")

	_meetingActionLog.fillFieldMap()

	return _meetingActionLog
}

type meetingActionLog struct {
	meetingActionLogDo meetingActionLogDo

	ALL       field.Asterisk
	ID        field.Uint   // 主键ID
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 删除时间
	RoomID    field.Uint   // 会议ID
	UserID    field.Uint   // 操作用户ID
	Action    field.String // 动作名称
	Detail    field.String // 动作详情

	fieldMap map[string]field.Expr
}

func (m meetingActionLog) Table(newTableName string) *meetingActionLog {
	m.meetingActionLogDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m meetingActionLog) As(alias string) *meetingActionLog {
	m.meetingActionLogDo.DO = *(m.meetingActionLogDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *meetingActionLog) updateTableName(table string) *meetingActionLog {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")
	m.RoomID = field.NewUint(table, "room_id")
	m.UserID = field.NewUint(table, "user_id")
	m.Action = field.NewString(table, "action")
	m.Detail = field.NewString(table, "detail")

	m.fillFieldMap()

	return m
}

func (m *meetingActionLog) WithContext(ctx context.Context) IMeetingActionLogDo {
	return m.meetingActionLogDo.WithContext(ctx)
}

func (m meetingActionLog) TableName() string { return m.meetingActionLogDo.TableName() }

func (m meetingActionLog) Alias() string { return m.meetingActionLogDo.Alias() }

func (m meetingActionLog) Columns(cols ...field.Expr) gen.Columns {
	return m.meetingActionLogDo.Columns(cols...)
}

func (m *meetingActionLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *meetingActionLog) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 8)
	m.fieldMap["id"] = m.ID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
	m.fieldMap["room_id"] = m.RoomID
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["action"] = m.Action
	m.fieldMap["detail"] = m.Detail
}

func (m meetingActionLog) clone(db *gorm.DB) meetingActionLog {
	m.meetingActionLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m meetingActionLog) replaceDB(db *gorm.DB) meetingActionLog {
	m.meetingActionLogDo.ReplaceDB(db)
	return m
}

type meetingActionLogDo struct{ gen.DO }

type IMeetingActionLogDo interface {
	gen.SubQuery
	Debug() IMeetingActionLogDo
	WithContext(ctx context.Context) IMeetingActionLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMeetingActionLogDo
	WriteDB() IMeetingActionLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMeetingActionLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMeetingActionLogDo
	Not(conds ...gen.Condition) IMeetingActionLogDo
	Or(conds ...gen.Condition) IMeetingActionLogDo
	Select(conds ...field.Expr) IMeetingActionLogDo
	Where(conds ...gen.Condition) IMeetingActionLogDo
	Order(conds ...field.Expr) IMeetingActionLogDo
	Distinct(cols ...field.Expr) IMeetingActionLogDo
	Omit(cols ...field.Expr) IMeetingActionLogDo
	Join(table schema.Tabler, on ...field.Expr) IMeetingActionLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMeetingActionLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMeetingActionLogDo
	Group(cols ...field.Expr) IMeetingActionLogDo
	Having(conds ...gen.Condition) IMeetingActionLogDo
	Limit(limit int) IMeetingActionLogDo
	Offset(offset int) IMeetingActionLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMeetingActionLogDo
	Unscoped() IMeetingActionLogDo
	Create(values ...*models.MeetingActionLog) error
	CreateInBatches(values []*models.MeetingActionLog, batchSize int) error
	Save(values ...*models.MeetingActionLog) error
	First() (*models.MeetingActionLog, error)
	Take() (*models.MeetingActionLog, error)
	Last() (*models.MeetingActionLog, error)
	Find() ([]*models.MeetingActionLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MeetingActionLog, err error)
	FindInBatches(result *[]*models.MeetingActionLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.MeetingActionLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMeetingActionLogDo
	Assign(attrs ...field.AssignExpr) IMeetingActionLogDo
	Joins(fields ...field.RelationField) IMeetingActionLogDo
	Preload(fields ...field.RelationField) IMeetingActionLogDo
	FirstOrInit() (*models.MeetingActionLog, error)
	FirstOrCreate() (*models.MeetingActionLog, error)
	FindByPage(offset int, limit int) (result []*models.MeetingActionLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMeetingActionLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m meetingActionLogDo) Debug() IMeetingActionLogDo {
	return m.withDO(m.DO.Debug())
}

func (m meetingActionLogDo) WithContext(ctx context.Context) IMeetingActionLogDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m meetingActionLogDo) ReadDB() IMeetingActionLogDo {
	return m.Clauses(dbresolver.Read)
}

func (m meetingActionLogDo) WriteDB() IMeetingActionLogDo {
	return m.Clauses(dbresolver.Write)
}

func (m meetingActionLogDo) Session(config *gorm.Session) IMeetingActionLogDo {
	return m.withDO(m.DO.Session(config))
}

func (m meetingActionLogDo) Clauses(conds ...clause.Expression) IMeetingActionLogDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m meetingActionLogDo) Returning(value interface{}, columns ...string) IMeetingActionLogDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m meetingActionLogDo) Not(conds ...gen.Condition) IMeetingActionLogDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m meetingActionLogDo) Or(conds ...gen.Condition) IMeetingActionLogDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m meetingActionLogDo) Select(conds ...field.Expr) IMeetingActionLogDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m meetingActionLogDo) Where(conds ...gen.Condition) IMeetingActionLogDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m meetingActionLogDo) Order(conds ...field.Expr) IMeetingActionLogDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m meetingActionLogDo) Distinct(cols ...field.Expr) IMeetingActionLogDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m meetingActionLogDo) Omit(cols ...field.Expr) IMeetingActionLogDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m meetingActionLogDo) Join(table schema.Tabler, on ...field.Expr) IMeetingActionLogDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m meetingActionLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMeetingActionLogDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m meetingActionLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IMeetingActionLogDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m meetingActionLogDo) Group(cols ...field.Expr) IMeetingActionLogDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m meetingActionLogDo) Having(conds ...gen.Condition) IMeetingActionLogDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m meetingActionLogDo) Limit(limit int) IMeetingActionLogDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m meetingActionLogDo) Offset(offset int) IMeetingActionLogDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m meetingActionLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMeetingActionLogDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m meetingActionLogDo) Unscoped() IMeetingActionLogDo {
	return m.withDO(m.DO.Unscoped())
}

func (m meetingActionLogDo) Create(values ...*models.MeetingActionLog) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m meetingActionLogDo) CreateInBatches(values []*models.MeetingActionLog, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m meetingActionLogDo) Save(values ...*models.MeetingActionLog) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m meetingActionLogDo) First() (*models.MeetingActionLog, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingActionLog), nil
	}
}

func (m meetingActionLogDo) Take() (*models.MeetingActionLog, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingActionLog), nil
	}
}

func (m meetingActionLogDo) Last() (*models.MeetingActionLog, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingActionLog), nil
	}
}

func (m meetingActionLogDo) Find() ([]*models.MeetingActionLog, error) {
	result, err := m.DO.Find()
	return result.([]*models.MeetingActionLog), err
}

func (m meetingActionLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MeetingActionLog, err error) {
	buf := make([]*models.MeetingActionLog, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m meetingActionLogDo) FindInBatches(result *[]*models.MeetingActionLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m meetingActionLogDo) Attrs(attrs ...field.AssignExpr) IMeetingActionLogDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m meetingActionLogDo) Assign(attrs ...field.AssignExpr) IMeetingActionLogDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m meetingActionLogDo) Joins(fields ...field.RelationField) IMeetingActionLogDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m meetingActionLogDo) Preload(fields ...field.RelationField) IMeetingActionLogDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m meetingActionLogDo) FirstOrInit() (*models.MeetingActionLog, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingActionLog), nil
	}
}

func (m meetingActionLogDo) FirstOrCreate() (*models.MeetingActionLog, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingActionLog), nil
	}
}

func (m meetingActionLogDo) FindByPage(offset int, limit int) (result []*models.MeetingActionLog, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m meetingActionLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m meetingActionLogDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m meetingActionLogDo) Delete(models ...*models.MeetingActionLog) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *meetingActionLogDo) withDO(do gen.Dao) *meetingActionLogDo {
	m.DO = *do.(*gen.DO)
	return m
}
