// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"fast-gin/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMeetingInvitation(db *gorm.DB, opts ...gen.DOOption) meetingInvitation {
	_meetingInvitation := meetingInvitation{}

	_meetingInvitation.meetingInvitationDo.UseDB(db, opts...)
	_meetingInvitation.meetingInvitationDo.UseModel(&models.MeetingInvitation{})

	tableName := _meetingInvitation.meetingInvitationDo.TableName()
	_meetingInvitation.ALL = field.NewAsterisk(tableName)
	_meetingInvitation.ID = field.NewUint(tableName, "id")
	_meetingInvitation.CreatedAt = field.NewTime(tableName, "created_at")
	_meetingInvitation.UpdatedAt = field.NewTime(tableName, "updated_at")
	_meetingInvitation.DeletedAt = field.NewField(tableName, "deleted_at")
	_meetingInvitation.RoomID = field.NewUint(tableName, "room_id")
	_meetingInvitation.SenderID = field.NewUint(tableName, "sender_id")
	_meetingInvitation.ReceiverID = field.NewUint(tableName, "receiver_id")
	_meetingInvitation.InviteCode = field.NewString(tableName, "invite_code")
	_meetingInvitation.Status = field.NewInt8(tableName, "status")
	_meetingInvitation.ExpiredAt = field.NewInt64(tableName, "expired_at")

	_meetingInvitation.fillFieldMap()

	return _meetingInvitation
}

type meetingInvitation struct {
	meetingInvitationDo meetingInvitationDo

	ALL        field.Asterisk
	ID         field.Uint   // 主键ID
	CreatedAt  field.Time   // 创建时间
	UpdatedAt  field.Time   // 更新时间
	DeletedAt  field.Field  // 删除时间
	RoomID     field.Uint   // 会议ID
	SenderID   field.Uint   // 邀请发送者ID
	ReceiverID field.Uint   // 被邀请者ID
	InviteCode field.String // 邀请码
	Status     field.Int8   // 邀请状态 0待接受 1已接受 2已拒绝 3已过期
	ExpiredAt  field.Int64  // 过期时间戳

	fieldMap map[string]field.Expr
}

func (m meetingInvitation) Table(newTableName string) *meetingInvitation {
	m.meetingInvitationDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m meetingInvitation) As(alias string) *meetingInvitation {
	m.meetingInvitationDo.DO = *(m.meetingInvitationDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *meetingInvitation) updateTableName(table string) *meetingInvitation {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")
	m.RoomID = field.NewUint(table, "room_id")
	m.SenderID = field.NewUint(table, "sender_id")
	m.ReceiverID = field.NewUint(table, "receiver_id")
	m.InviteCode = field.NewString(table, "invite_code")
	m.Status = field.NewInt8(table, "status")
	m.ExpiredAt = field.NewInt64(table, "expired_at")

	m.fillFieldMap()

	return m
}

func (m *meetingInvitation) WithContext(ctx context.Context) IMeetingInvitationDo {
	return m.meetingInvitationDo.WithContext(ctx)
}

func (m meetingInvitation) TableName() string { return m.meetingInvitationDo.TableName() }

func (m meetingInvitation) Alias() string { return m.meetingInvitationDo.Alias() }

func (m meetingInvitation) Columns(cols ...field.Expr) gen.Columns {
	return m.meetingInvitationDo.Columns(cols...)
}

func (m *meetingInvitation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *meetingInvitation) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 10)
	m.fieldMap["id"] = m.ID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
	m.fieldMap["room_id"] = m.RoomID
	m.fieldMap["sender_id"] = m.SenderID
	m.fieldMap["receiver_id"] = m.ReceiverID
	m.fieldMap["invite_code"] = m.InviteCode
	m.fieldMap["status"] = m.Status
	m.fieldMap["expired_at"] = m.ExpiredAt
}

func (m meetingInvitation) clone(db *gorm.DB) meetingInvitation {
	m.meetingInvitationDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m meetingInvitation) replaceDB(db *gorm.DB) meetingInvitation {
	m.meetingInvitationDo.ReplaceDB(db)
	return m
}

type meetingInvitationDo struct{ gen.DO }

type IMeetingInvitationDo interface {
	gen.SubQuery
	Debug() IMeetingInvitationDo
	WithContext(ctx context.Context) IMeetingInvitationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMeetingInvitationDo
	WriteDB() IMeetingInvitationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMeetingInvitationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMeetingInvitationDo
	Not(conds ...gen.Condition) IMeetingInvitationDo
	Or(conds ...gen.Condition) IMeetingInvitationDo
	Select(conds ...field.Expr) IMeetingInvitationDo
	Where(conds ...gen.Condition) IMeetingInvitationDo
	Order(conds ...field.Expr) IMeetingInvitationDo
	Distinct(cols ...field.Expr) IMeetingInvitationDo
	Omit(cols ...field.Expr) IMeetingInvitationDo
	Join(table schema.Tabler, on ...field.Expr) IMeetingInvitationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMeetingInvitationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMeetingInvitationDo
	Group(cols ...field.Expr) IMeetingInvitationDo
	Having(conds ...gen.Condition) IMeetingInvitationDo
	Limit(limit int) IMeetingInvitationDo
	Offset(offset int) IMeetingInvitationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMeetingInvitationDo
	Unscoped() IMeetingInvitationDo
	Create(values ...*models.MeetingInvitation) error
	CreateInBatches(values []*models.MeetingInvitation, batchSize int) error
	Save(values ...*models.MeetingInvitation) error
	First() (*models.MeetingInvitation, error)
	Take() (*models.MeetingInvitation, error)
	Last() (*models.MeetingInvitation, error)
	Find() ([]*models.MeetingInvitation, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MeetingInvitation, err error)
	FindInBatches(result *[]*models.MeetingInvitation, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.MeetingInvitation) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMeetingInvitationDo
	Assign(attrs ...field.AssignExpr) IMeetingInvitationDo
	Joins(fields ...field.RelationField) IMeetingInvitationDo
	Preload(fields ...field.RelationField) IMeetingInvitationDo
	FirstOrInit() (*models.MeetingInvitation, error)
	FirstOrCreate() (*models.MeetingInvitation, error)
	FindByPage(offset int, limit int) (result []*models.MeetingInvitation, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMeetingInvitationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m meetingInvitationDo) Debug() IMeetingInvitationDo {
	return m.withDO(m.DO.Debug())
}

func (m meetingInvitationDo) WithContext(ctx context.Context) IMeetingInvitationDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m meetingInvitationDo) ReadDB() IMeetingInvitationDo {
	return m.Clauses(dbresolver.Read)
}

func (m meetingInvitationDo) WriteDB() IMeetingInvitationDo {
	return m.Clauses(dbresolver.Write)
}

func (m meetingInvitationDo) Session(config *gorm.Session) IMeetingInvitationDo {
	return m.withDO(m.DO.Session(config))
}

func (m meetingInvitationDo) Clauses(conds ...clause.Expression) IMeetingInvitationDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m meetingInvitationDo) Returning(value interface{}, columns ...string) IMeetingInvitationDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m meetingInvitationDo) Not(conds ...gen.Condition) IMeetingInvitationDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m meetingInvitationDo) Or(conds ...gen.Condition) IMeetingInvitationDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m meetingInvitationDo) Select(conds ...field.Expr) IMeetingInvitationDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m meetingInvitationDo) Where(conds ...gen.Condition) IMeetingInvitationDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m meetingInvitationDo) Order(conds ...field.Expr) IMeetingInvitationDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m meetingInvitationDo) Distinct(cols ...field.Expr) IMeetingInvitationDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m meetingInvitationDo) Omit(cols ...field.Expr) IMeetingInvitationDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m meetingInvitationDo) Join(table schema.Tabler, on ...field.Expr) IMeetingInvitationDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m meetingInvitationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMeetingInvitationDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m meetingInvitationDo) RightJoin(table schema.Tabler, on ...field.Expr) IMeetingInvitationDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m meetingInvitationDo) Group(cols ...field.Expr) IMeetingInvitationDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m meetingInvitationDo) Having(conds ...gen.Condition) IMeetingInvitationDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m meetingInvitationDo) Limit(limit int) IMeetingInvitationDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m meetingInvitationDo) Offset(offset int) IMeetingInvitationDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m meetingInvitationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMeetingInvitationDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m meetingInvitationDo) Unscoped() IMeetingInvitationDo {
	return m.withDO(m.DO.Unscoped())
}

func (m meetingInvitationDo) Create(values ...*models.MeetingInvitation) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m meetingInvitationDo) CreateInBatches(values []*models.MeetingInvitation, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m meetingInvitationDo) Save(values ...*models.MeetingInvitation) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m meetingInvitationDo) First() (*models.MeetingInvitation, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingInvitation), nil
	}
}

func (m meetingInvitationDo) Take() (*models.MeetingInvitation, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingInvitation), nil
	}
}

func (m meetingInvitationDo) Last() (*models.MeetingInvitation, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingInvitation), nil
	}
}

func (m meetingInvitationDo) Find() ([]*models.MeetingInvitation, error) {
	result, err := m.DO.Find()
	return result.([]*models.MeetingInvitation), err
}

func (m meetingInvitationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MeetingInvitation, err error) {
	buf := make([]*models.MeetingInvitation, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m meetingInvitationDo) FindInBatches(result *[]*models.MeetingInvitation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m meetingInvitationDo) Attrs(attrs ...field.AssignExpr) IMeetingInvitationDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m meetingInvitationDo) Assign(attrs ...field.AssignExpr) IMeetingInvitationDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m meetingInvitationDo) Joins(fields ...field.RelationField) IMeetingInvitationDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m meetingInvitationDo) Preload(fields ...field.RelationField) IMeetingInvitationDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m meetingInvitationDo) FirstOrInit() (*models.MeetingInvitation, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingInvitation), nil
	}
}

func (m meetingInvitationDo) FirstOrCreate() (*models.MeetingInvitation, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.MeetingInvitation), nil
	}
}

func (m meetingInvitationDo) FindByPage(offset int, limit int) (result []*models.MeetingInvitation, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m meetingInvitationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m meetingInvitationDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m meetingInvitationDo) Delete(models ...*models.MeetingInvitation) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *meetingInvitationDo) withDO(do gen.Dao) *meetingInvitationDo {
	m.DO = *do.(*gen.DO)
	return m
}
