// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"fast-gin/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newRecordingFile(db *gorm.DB, opts ...gen.DOOption) recordingFile {
	_recordingFile := recordingFile{}

	_recordingFile.recordingFileDo.UseDB(db, opts...)
	_recordingFile.recordingFileDo.UseModel(&models.RecordingFile{})

	tableName := _recordingFile.recordingFileDo.TableName()
	_recordingFile.ALL = field.NewAsterisk(tableName)
	_recordingFile.ID = field.NewUint(tableName, "id")
	_recordingFile.CreatedAt = field.NewTime(tableName, "created_at")
	_recordingFile.UpdatedAt = field.NewTime(tableName, "updated_at")
	_recordingFile.DeletedAt = field.NewField(tableName, "deleted_at")
	_recordingFile.RecordingID = field.NewUint(tableName, "recording_id")
	_recordingFile.ClientID = field.NewString(tableName, "client_id")
	_recordingFile.UserID = field.NewUint(tableName, "user_id")
	_recordingFile.DisplayName = field.NewString(tableName, "display_name")
	_recordingFile.FilePath = field.NewString(tableName, "file_path")
	_recordingFile.Kind = field.NewString(tableName, "kind")
	_recordingFile.Codec = field.NewString(tableName, "codec")
	_recordingFile.FileSize = field.NewInt64(tableName, "file_size")

	_recordingFile.fillFieldMap()

	return _recordingFile
}

type recordingFile struct {
	recordingFileDo recordingFileDo

	ALL         field.Asterisk
	ID          field.Uint   // 主键ID
	CreatedAt   field.Time   // 创建时间
	UpdatedAt   field.Time   // 更新时间
	DeletedAt   field.Field  // 删除时间
	RecordingID field.Uint   // 录制ID
	ClientID    field.String // 客户端ID
	UserID      field.Uint   // 用户ID
	DisplayName field.String // 显示名称
	FilePath    field.String // 文件路径
	Kind        field.String // 文件类型
	Codec       field.String // 编码格式
	FileSize    field.Int64  // 文件大小

	fieldMap map[string]field.Expr
}

func (r recordingFile) Table(newTableName string) *recordingFile {
	r.recordingFileDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r recordingFile) As(alias string) *recordingFile {
	r.recordingFileDo.DO = *(r.recordingFileDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *recordingFile) updateTableName(table string) *recordingFile {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewUint(table, "id")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")
	r.RecordingID = field.NewUint(table, "recording_id")
	r.ClientID = field.NewString(table, "client_id")
	r.UserID = field.NewUint(table, "user_id")
	r.DisplayName = field.NewString(table, "display_name")
	r.FilePath = field.NewString(table, "file_path")
	r.Kind = field.NewString(table, "kind")
	r.Codec = field.NewString(table, "codec")
	r.FileSize = field.NewInt64(table, "file_size")

	r.fillFieldMap()

	return r
}

func (r *recordingFile) WithContext(ctx context.Context) IRecordingFileDo {
	return r.recordingFileDo.WithContext(ctx)
}

func (r recordingFile) TableName() string { return r.recordingFileDo.TableName() }

func (r recordingFile) Alias() string { return r.recordingFileDo.Alias() }

func (r recordingFile) Columns(cols ...field.Expr) gen.Columns {
	return r.recordingFileDo.Columns(cols...)
}

func (r *recordingFile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *recordingFile) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 12)
	r.fieldMap["id"] = r.ID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
	r.fieldMap["recording_id"] = r.RecordingID
	r.fieldMap["client_id"] = r.ClientID
	r.fieldMap["user_id"] = r.UserID
	r.fieldMap["display_name"] = r.DisplayName
	r.fieldMap["file_path"] = r.FilePath
	r.fieldMap["kind"] = r.Kind
	r.fieldMap["codec"] = r.Codec
	r.fieldMap["file_size"] = r.FileSize
}

func (r recordingFile) clone(db *gorm.DB) recordingFile {
	r.recordingFileDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r recordingFile) replaceDB(db *gorm.DB) recordingFile {
	r.recordingFileDo.ReplaceDB(db)
	return r
}

type recordingFileDo struct{ gen.DO }

type IRecordingFileDo interface {
	gen.SubQuery
	Debug() IRecordingFileDo
	WithContext(ctx context.Context) IRecordingFileDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRecordingFileDo
	WriteDB() IRecordingFileDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRecordingFileDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRecordingFileDo
	Not(conds ...gen.Condition) IRecordingFileDo
	Or(conds ...gen.Condition) IRecordingFileDo
	Select(conds ...field.Expr) IRecordingFileDo
	Where(conds ...gen.Condition) IRecordingFileDo
	Order(conds ...field.Expr) IRecordingFileDo
	Distinct(cols ...field.Expr) IRecordingFileDo
	Omit(cols ...field.Expr) IRecordingFileDo
	Join(table schema.Tabler, on ...field.Expr) IRecordingFileDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRecordingFileDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRecordingFileDo
	Group(cols ...field.Expr) IRecordingFileDo
	Having(conds ...gen.Condition) IRecordingFileDo
	Limit(limit int) IRecordingFileDo
	Offset(offset int) IRecordingFileDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRecordingFileDo
	Unscoped() IRecordingFileDo
	Create(values ...*models.RecordingFile) error
	CreateInBatches(values []*models.RecordingFile, batchSize int) error
	Save(values ...*models.RecordingFile) error
	First() (*models.RecordingFile, error)
	Take() (*models.RecordingFile, error)
	Last() (*models.RecordingFile, error)
	Find() ([]*models.RecordingFile, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.RecordingFile, err error)
	FindInBatches(result *[]*models.RecordingFile, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.RecordingFile) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRecordingFileDo
	Assign(attrs ...field.AssignExpr) IRecordingFileDo
	Joins(fields ...field.RelationField) IRecordingFileDo
	Preload(fields ...field.RelationField) IRecordingFileDo
	FirstOrInit() (*models.RecordingFile, error)
	FirstOrCreate() (*models.RecordingFile, error)
	FindByPage(offset int, limit int) (result []*models.RecordingFile, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRecordingFileDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r recordingFileDo) Debug() IRecordingFileDo {
	return r.withDO(r.DO.Debug())
}

func (r recordingFileDo) WithContext(ctx context.Context) IRecordingFileDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r recordingFileDo) ReadDB() IRecordingFileDo {
	return r.Clauses(dbresolver.Read)
}

func (r recordingFileDo) WriteDB() IRecordingFileDo {
	return r.Clauses(dbresolver.Write)
}

func (r recordingFileDo) Session(config *gorm.Session) IRecordingFileDo {
	return r.withDO(r.DO.Session(config))
}

func (r recordingFileDo) Clauses(conds ...clause.Expression) IRecordingFileDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r recordingFileDo) Returning(value interface{}, columns ...string) IRecordingFileDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r recordingFileDo) Not(conds ...gen.Condition) IRecordingFileDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r recordingFileDo) Or(conds ...gen.Condition) IRecordingFileDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r recordingFileDo) Select(conds ...field.Expr) IRecordingFileDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r recordingFileDo) Where(conds ...gen.Condition) IRecordingFileDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r recordingFileDo) Order(conds ...field.Expr) IRecordingFileDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r recordingFileDo) Distinct(cols ...field.Expr) IRecordingFileDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r recordingFileDo) Omit(cols ...field.Expr) IRecordingFileDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r recordingFileDo) Join(table schema.Tabler, on ...field.Expr) IRecordingFileDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r recordingFileDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRecordingFileDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r recordingFileDo) RightJoin(table schema.Tabler, on ...field.Expr) IRecordingFileDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r recordingFileDo) Group(cols ...field.Expr) IRecordingFileDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r recordingFileDo) Having(conds ...gen.Condition) IRecordingFileDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r recordingFileDo) Limit(limit int) IRecordingFileDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r recordingFileDo) Offset(offset int) IRecordingFileDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r recordingFileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRecordingFileDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r recordingFileDo) Unscoped() IRecordingFileDo {
	return r.withDO(r.DO.Unscoped())
}

func (r recordingFileDo) Create(values ...*models.RecordingFile) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r recordingFileDo) CreateInBatches(values []*models.RecordingFile, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r recordingFileDo) Save(values ...*models.RecordingFile) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r recordingFileDo) First() (*models.RecordingFile, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.RecordingFile), nil
	}
}

func (r recordingFileDo) Take() (*models.RecordingFile, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.RecordingFile), nil
	}
}

func (r recordingFileDo) Last() (*models.RecordingFile, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.RecordingFile), nil
	}
}

func (r recordingFileDo) Find() ([]*models.RecordingFile, error) {
	result, err := r.DO.Find()
	return result.([]*models.RecordingFile), err
}

func (r recordingFileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.RecordingFile, err error) {
	buf := make([]*models.RecordingFile, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r recordingFileDo) FindInBatches(result *[]*models.RecordingFile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r recordingFileDo) Attrs(attrs ...field.AssignExpr) IRecordingFileDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r recordingFileDo) Assign(attrs ...field.AssignExpr) IRecordingFileDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r recordingFileDo) Joins(fields ...field.RelationField) IRecordingFileDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r recordingFileDo) Preload(fields ...field.RelationField) IRecordingFileDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r recordingFileDo) FirstOrInit() (*models.RecordingFile, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.RecordingFile), nil
	}
}

func (r recordingFileDo) FirstOrCreate() (*models.RecordingFile, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.RecordingFile), nil
	}
}

func (r recordingFileDo) FindByPage(offset int, limit int) (result []*models.RecordingFile, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r recordingFileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r recordingFileDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r recordingFileDo) Delete(models ...*models.RecordingFile) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *recordingFileDo) withDO(do gen.Dao) *recordingFileDo {
	r.DO = *do.(*gen.DO)
	return r
}
