// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"fast-gin/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newRecording(db *gorm.DB, opts ...gen.DOOption) recording {
	_recording := recording{}

	_recording.recordingDo.UseDB(db, opts...)
	_recording.recordingDo.UseModel(&models.Recording{})

	tableName := _recording.recordingDo.TableName()
	_recording.ALL = field.NewAsterisk(tableName)
	_recording.ID = field.NewUint(tableName, "id")
	_recording.CreatedAt = field.NewTime(tableName, "created_at")
	_recording.UpdatedAt = field.NewTime(tableName, "updated_at")
	_recording.DeletedAt = field.NewField(tableName, "deleted_at")
	_recording.MeetingID = field.NewUint(tableName, "meeting_id")
	_recording.RoomNo = field.NewUint(tableName, "room_no")
	_recording.HostID = field.NewUint(tableName, "host_id")
	_recording.StartedAt = field.NewTime(tableName, "started_at")
	_recording.EndedAt = field.NewTime(tableName, "ended_at")
	_recording.DurationMs = field.NewInt64(tableName, "duration_ms")
	_recording.Status = field.NewString(tableName, "status")
	_recording.FileCount = field.NewInt(tableName, "file_count")
	_recording.StoragePath = field.NewString(tableName, "storage_path")
	_recording.UserID = field.NewUint(tableName, "user_id")
	_recording.FileName = field.NewString(tableName, "file_name")
	_recording.FilePath = field.NewString(tableName, "file_path")
	_recording.FileSize = field.NewInt64(tableName, "file_size")
	_recording.Duration = field.NewFloat64(tableName, "duration")

	_recording.fillFieldMap()

	return _recording
}

type recording struct {
	recordingDo recordingDo

	ALL         field.Asterisk
	ID          field.Uint    // 主键ID
	CreatedAt   field.Time    // 创建时间
	UpdatedAt   field.Time    // 更新时间
	DeletedAt   field.Field   // 删除时间
	MeetingID   field.Uint    // 关联会议ID
	RoomNo      field.Uint    // 会议房间号
	HostID      field.Uint    // 主持人用户ID
	StartedAt   field.Time    // 录制开始时间
	EndedAt     field.Time    // 录制结束时间
	DurationMs  field.Int64   // 录制时长(毫秒)
	Status      field.String  // recording/completed/failed
	FileCount   field.Int     // 文件数量
	StoragePath field.String  // 录制存储目录
	UserID      field.Uint    // 上传用户ID
	FileName    field.String  // 原始文件名
	FilePath    field.String  // 文件存储路径
	FileSize    field.Int64   // 文件大小(字节)
	Duration    field.Float64 // 录制时长(秒)

	fieldMap map[string]field.Expr
}

func (r recording) Table(newTableName string) *recording {
	r.recordingDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r recording) As(alias string) *recording {
	r.recordingDo.DO = *(r.recordingDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *recording) updateTableName(table string) *recording {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewUint(table, "id")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")
	r.MeetingID = field.NewUint(table, "meeting_id")
	r.RoomNo = field.NewUint(table, "room_no")
	r.HostID = field.NewUint(table, "host_id")
	r.StartedAt = field.NewTime(table, "started_at")
	r.EndedAt = field.NewTime(table, "ended_at")
	r.DurationMs = field.NewInt64(table, "duration_ms")
	r.Status = field.NewString(table, "status")
	r.FileCount = field.NewInt(table, "file_count")
	r.StoragePath = field.NewString(table, "storage_path")
	r.UserID = field.NewUint(table, "user_id")
	r.FileName = field.NewString(table, "file_name")
	r.FilePath = field.NewString(table, "file_path")
	r.FileSize = field.NewInt64(table, "file_size")
	r.Duration = field.NewFloat64(table, "duration")

	r.fillFieldMap()

	return r
}

func (r *recording) WithContext(ctx context.Context) IRecordingDo {
	return r.recordingDo.WithContext(ctx)
}

func (r recording) TableName() string { return r.recordingDo.TableName() }

func (r recording) Alias() string { return r.recordingDo.Alias() }

func (r recording) Columns(cols ...field.Expr) gen.Columns { return r.recordingDo.Columns(cols...) }

func (r *recording) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *recording) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 18)
	r.fieldMap["id"] = r.ID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
	r.fieldMap["meeting_id"] = r.MeetingID
	r.fieldMap["room_no"] = r.RoomNo
	r.fieldMap["host_id"] = r.HostID
	r.fieldMap["started_at"] = r.StartedAt
	r.fieldMap["ended_at"] = r.EndedAt
	r.fieldMap["duration_ms"] = r.DurationMs
	r.fieldMap["status"] = r.Status
	r.fieldMap["file_count"] = r.FileCount
	r.fieldMap["storage_path"] = r.StoragePath
	r.fieldMap["user_id"] = r.UserID
	r.fieldMap["file_name"] = r.FileName
	r.fieldMap["file_path"] = r.FilePath
	r.fieldMap["file_size"] = r.FileSize
	r.fieldMap["duration"] = r.Duration
}

func (r recording) clone(db *gorm.DB) recording {
	r.recordingDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r recording) replaceDB(db *gorm.DB) recording {
	r.recordingDo.ReplaceDB(db)
	return r
}

type recordingDo struct{ gen.DO }

type IRecordingDo interface {
	gen.SubQuery
	Debug() IRecordingDo
	WithContext(ctx context.Context) IRecordingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRecordingDo
	WriteDB() IRecordingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRecordingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRecordingDo
	Not(conds ...gen.Condition) IRecordingDo
	Or(conds ...gen.Condition) IRecordingDo
	Select(conds ...field.Expr) IRecordingDo
	Where(conds ...gen.Condition) IRecordingDo
	Order(conds ...field.Expr) IRecordingDo
	Distinct(cols ...field.Expr) IRecordingDo
	Omit(cols ...field.Expr) IRecordingDo
	Join(table schema.Tabler, on ...field.Expr) IRecordingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRecordingDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRecordingDo
	Group(cols ...field.Expr) IRecordingDo
	Having(conds ...gen.Condition) IRecordingDo
	Limit(limit int) IRecordingDo
	Offset(offset int) IRecordingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRecordingDo
	Unscoped() IRecordingDo
	Create(values ...*models.Recording) error
	CreateInBatches(values []*models.Recording, batchSize int) error
	Save(values ...*models.Recording) error
	First() (*models.Recording, error)
	Take() (*models.Recording, error)
	Last() (*models.Recording, error)
	Find() ([]*models.Recording, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Recording, err error)
	FindInBatches(result *[]*models.Recording, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Recording) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRecordingDo
	Assign(attrs ...field.AssignExpr) IRecordingDo
	Joins(fields ...field.RelationField) IRecordingDo
	Preload(fields ...field.RelationField) IRecordingDo
	FirstOrInit() (*models.Recording, error)
	FirstOrCreate() (*models.Recording, error)
	FindByPage(offset int, limit int) (result []*models.Recording, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRecordingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r recordingDo) Debug() IRecordingDo {
	return r.withDO(r.DO.Debug())
}

func (r recordingDo) WithContext(ctx context.Context) IRecordingDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r recordingDo) ReadDB() IRecordingDo {
	return r.Clauses(dbresolver.Read)
}

func (r recordingDo) WriteDB() IRecordingDo {
	return r.Clauses(dbresolver.Write)
}

func (r recordingDo) Session(config *gorm.Session) IRecordingDo {
	return r.withDO(r.DO.Session(config))
}

func (r recordingDo) Clauses(conds ...clause.Expression) IRecordingDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r recordingDo) Returning(value interface{}, columns ...string) IRecordingDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r recordingDo) Not(conds ...gen.Condition) IRecordingDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r recordingDo) Or(conds ...gen.Condition) IRecordingDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r recordingDo) Select(conds ...field.Expr) IRecordingDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r recordingDo) Where(conds ...gen.Condition) IRecordingDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r recordingDo) Order(conds ...field.Expr) IRecordingDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r recordingDo) Distinct(cols ...field.Expr) IRecordingDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r recordingDo) Omit(cols ...field.Expr) IRecordingDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r recordingDo) Join(table schema.Tabler, on ...field.Expr) IRecordingDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r recordingDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRecordingDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r recordingDo) RightJoin(table schema.Tabler, on ...field.Expr) IRecordingDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r recordingDo) Group(cols ...field.Expr) IRecordingDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r recordingDo) Having(conds ...gen.Condition) IRecordingDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r recordingDo) Limit(limit int) IRecordingDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r recordingDo) Offset(offset int) IRecordingDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r recordingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRecordingDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r recordingDo) Unscoped() IRecordingDo {
	return r.withDO(r.DO.Unscoped())
}

func (r recordingDo) Create(values ...*models.Recording) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r recordingDo) CreateInBatches(values []*models.Recording, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r recordingDo) Save(values ...*models.Recording) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r recordingDo) First() (*models.Recording, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Recording), nil
	}
}

func (r recordingDo) Take() (*models.Recording, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Recording), nil
	}
}

func (r recordingDo) Last() (*models.Recording, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Recording), nil
	}
}

func (r recordingDo) Find() ([]*models.Recording, error) {
	result, err := r.DO.Find()
	return result.([]*models.Recording), err
}

func (r recordingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Recording, err error) {
	buf := make([]*models.Recording, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r recordingDo) FindInBatches(result *[]*models.Recording, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r recordingDo) Attrs(attrs ...field.AssignExpr) IRecordingDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r recordingDo) Assign(attrs ...field.AssignExpr) IRecordingDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r recordingDo) Joins(fields ...field.RelationField) IRecordingDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r recordingDo) Preload(fields ...field.RelationField) IRecordingDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r recordingDo) FirstOrInit() (*models.Recording, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Recording), nil
	}
}

func (r recordingDo) FirstOrCreate() (*models.Recording, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Recording), nil
	}
}

func (r recordingDo) FindByPage(offset int, limit int) (result []*models.Recording, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r recordingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r recordingDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r recordingDo) Delete(models ...*models.Recording) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *recordingDo) withDO(do gen.Dao) *recordingDo {
	r.DO = *do.(*gen.DO)
	return r
}
