// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"fast-gin/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSignalMessage(db *gorm.DB, opts ...gen.DOOption) signalMessage {
	_signalMessage := signalMessage{}

	_signalMessage.signalMessageDo.UseDB(db, opts...)
	_signalMessage.signalMessageDo.UseModel(&models.SignalMessage{})

	tableName := _signalMessage.signalMessageDo.TableName()
	_signalMessage.ALL = field.NewAsterisk(tableName)
	_signalMessage.ID = field.NewUint(tableName, "id")
	_signalMessage.CreatedAt = field.NewTime(tableName, "created_at")
	_signalMessage.UpdatedAt = field.NewTime(tableName, "updated_at")
	_signalMessage.DeletedAt = field.NewField(tableName, "deleted_at")
	_signalMessage.RoomID = field.NewUint(tableName, "room_id")
	_signalMessage.SenderID = field.NewUint(tableName, "sender_id")
	_signalMessage.MessageType = field.NewString(tableName, "message_type")
	_signalMessage.MessageContent = field.NewString(tableName, "message_content")

	_signalMessage.fillFieldMap()

	return _signalMessage
}

type signalMessage struct {
	signalMessageDo signalMessageDo

	ALL            field.Asterisk
	ID             field.Uint   // 主键ID
	CreatedAt      field.Time   // 创建时间
	UpdatedAt      field.Time   // 更新时间
	DeletedAt      field.Field  // 删除时间
	RoomID         field.Uint   // 会议ID
	SenderID       field.Uint   // 发送者ID
	MessageType    field.String // 消息类型
	MessageContent field.String // 消息内容

	fieldMap map[string]field.Expr
}

func (s signalMessage) Table(newTableName string) *signalMessage {
	s.signalMessageDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s signalMessage) As(alias string) *signalMessage {
	s.signalMessageDo.DO = *(s.signalMessageDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *signalMessage) updateTableName(table string) *signalMessage {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.RoomID = field.NewUint(table, "room_id")
	s.SenderID = field.NewUint(table, "sender_id")
	s.MessageType = field.NewString(table, "message_type")
	s.MessageContent = field.NewString(table, "message_content")

	s.fillFieldMap()

	return s
}

func (s *signalMessage) WithContext(ctx context.Context) ISignalMessageDo {
	return s.signalMessageDo.WithContext(ctx)
}

func (s signalMessage) TableName() string { return s.signalMessageDo.TableName() }

func (s signalMessage) Alias() string { return s.signalMessageDo.Alias() }

func (s signalMessage) Columns(cols ...field.Expr) gen.Columns {
	return s.signalMessageDo.Columns(cols...)
}

func (s *signalMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *signalMessage) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["room_id"] = s.RoomID
	s.fieldMap["sender_id"] = s.SenderID
	s.fieldMap["message_type"] = s.MessageType
	s.fieldMap["message_content"] = s.MessageContent
}

func (s signalMessage) clone(db *gorm.DB) signalMessage {
	s.signalMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s signalMessage) replaceDB(db *gorm.DB) signalMessage {
	s.signalMessageDo.ReplaceDB(db)
	return s
}

type signalMessageDo struct{ gen.DO }

type ISignalMessageDo interface {
	gen.SubQuery
	Debug() ISignalMessageDo
	WithContext(ctx context.Context) ISignalMessageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISignalMessageDo
	WriteDB() ISignalMessageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISignalMessageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISignalMessageDo
	Not(conds ...gen.Condition) ISignalMessageDo
	Or(conds ...gen.Condition) ISignalMessageDo
	Select(conds ...field.Expr) ISignalMessageDo
	Where(conds ...gen.Condition) ISignalMessageDo
	Order(conds ...field.Expr) ISignalMessageDo
	Distinct(cols ...field.Expr) ISignalMessageDo
	Omit(cols ...field.Expr) ISignalMessageDo
	Join(table schema.Tabler, on ...field.Expr) ISignalMessageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISignalMessageDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISignalMessageDo
	Group(cols ...field.Expr) ISignalMessageDo
	Having(conds ...gen.Condition) ISignalMessageDo
	Limit(limit int) ISignalMessageDo
	Offset(offset int) ISignalMessageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISignalMessageDo
	Unscoped() ISignalMessageDo
	Create(values ...*models.SignalMessage) error
	CreateInBatches(values []*models.SignalMessage, batchSize int) error
	Save(values ...*models.SignalMessage) error
	First() (*models.SignalMessage, error)
	Take() (*models.SignalMessage, error)
	Last() (*models.SignalMessage, error)
	Find() ([]*models.SignalMessage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SignalMessage, err error)
	FindInBatches(result *[]*models.SignalMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SignalMessage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISignalMessageDo
	Assign(attrs ...field.AssignExpr) ISignalMessageDo
	Joins(fields ...field.RelationField) ISignalMessageDo
	Preload(fields ...field.RelationField) ISignalMessageDo
	FirstOrInit() (*models.SignalMessage, error)
	FirstOrCreate() (*models.SignalMessage, error)
	FindByPage(offset int, limit int) (result []*models.SignalMessage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISignalMessageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s signalMessageDo) Debug() ISignalMessageDo {
	return s.withDO(s.DO.Debug())
}

func (s signalMessageDo) WithContext(ctx context.Context) ISignalMessageDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s signalMessageDo) ReadDB() ISignalMessageDo {
	return s.Clauses(dbresolver.Read)
}

func (s signalMessageDo) WriteDB() ISignalMessageDo {
	return s.Clauses(dbresolver.Write)
}

func (s signalMessageDo) Session(config *gorm.Session) ISignalMessageDo {
	return s.withDO(s.DO.Session(config))
}

func (s signalMessageDo) Clauses(conds ...clause.Expression) ISignalMessageDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s signalMessageDo) Returning(value interface{}, columns ...string) ISignalMessageDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s signalMessageDo) Not(conds ...gen.Condition) ISignalMessageDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s signalMessageDo) Or(conds ...gen.Condition) ISignalMessageDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s signalMessageDo) Select(conds ...field.Expr) ISignalMessageDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s signalMessageDo) Where(conds ...gen.Condition) ISignalMessageDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s signalMessageDo) Order(conds ...field.Expr) ISignalMessageDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s signalMessageDo) Distinct(cols ...field.Expr) ISignalMessageDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s signalMessageDo) Omit(cols ...field.Expr) ISignalMessageDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s signalMessageDo) Join(table schema.Tabler, on ...field.Expr) ISignalMessageDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s signalMessageDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISignalMessageDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s signalMessageDo) RightJoin(table schema.Tabler, on ...field.Expr) ISignalMessageDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s signalMessageDo) Group(cols ...field.Expr) ISignalMessageDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s signalMessageDo) Having(conds ...gen.Condition) ISignalMessageDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s signalMessageDo) Limit(limit int) ISignalMessageDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s signalMessageDo) Offset(offset int) ISignalMessageDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s signalMessageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISignalMessageDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s signalMessageDo) Unscoped() ISignalMessageDo {
	return s.withDO(s.DO.Unscoped())
}

func (s signalMessageDo) Create(values ...*models.SignalMessage) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s signalMessageDo) CreateInBatches(values []*models.SignalMessage, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s signalMessageDo) Save(values ...*models.SignalMessage) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s signalMessageDo) First() (*models.SignalMessage, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SignalMessage), nil
	}
}

func (s signalMessageDo) Take() (*models.SignalMessage, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SignalMessage), nil
	}
}

func (s signalMessageDo) Last() (*models.SignalMessage, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SignalMessage), nil
	}
}

func (s signalMessageDo) Find() ([]*models.SignalMessage, error) {
	result, err := s.DO.Find()
	return result.([]*models.SignalMessage), err
}

func (s signalMessageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SignalMessage, err error) {
	buf := make([]*models.SignalMessage, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s signalMessageDo) FindInBatches(result *[]*models.SignalMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s signalMessageDo) Attrs(attrs ...field.AssignExpr) ISignalMessageDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s signalMessageDo) Assign(attrs ...field.AssignExpr) ISignalMessageDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s signalMessageDo) Joins(fields ...field.RelationField) ISignalMessageDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s signalMessageDo) Preload(fields ...field.RelationField) ISignalMessageDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s signalMessageDo) FirstOrInit() (*models.SignalMessage, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SignalMessage), nil
	}
}

func (s signalMessageDo) FirstOrCreate() (*models.SignalMessage, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SignalMessage), nil
	}
}

func (s signalMessageDo) FindByPage(offset int, limit int) (result []*models.SignalMessage, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s signalMessageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s signalMessageDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s signalMessageDo) Delete(models ...*models.SignalMessage) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *signalMessageDo) withDO(do gen.Dao) *signalMessageDo {
	s.DO = *do.(*gen.DO)
	return s
}
