// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"fast-gin/models"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newWhiteboard(db *gorm.DB, opts ...gen.DOOption) whiteboard {
	_whiteboard := whiteboard{}

	_whiteboard.whiteboardDo.UseDB(db, opts...)
	_whiteboard.whiteboardDo.UseModel(&models.Whiteboard{})

	tableName := _whiteboard.whiteboardDo.TableName()
	_whiteboard.ALL = field.NewAsterisk(tableName)
	_whiteboard.ID = field.NewUint(tableName, "id")
	_whiteboard.CreatedAt = field.NewTime(tableName, "created_at")
	_whiteboard.UpdatedAt = field.NewTime(tableName, "updated_at")
	_whiteboard.DeletedAt = field.NewField(tableName, "deleted_at")
	_whiteboard.RoomID = field.NewUint(tableName, "room_id")
	_whiteboard.CreatorID = field.NewUint(tableName, "creator_id")
	_whiteboard.Name = field.NewString(tableName, "name")
	_whiteboard.SnapshotFileID = field.NewUint(tableName, "snapshot_file_id")
	_whiteboard.DataJSON = field.NewString(tableName, "data_json")

	_whiteboard.fillFieldMap()

	return _whiteboard
}

type whiteboard struct {
	whiteboardDo whiteboardDo

	ALL            field.Asterisk
	ID             field.Uint   // 主键ID
	CreatedAt      field.Time   // 创建时间
	UpdatedAt      field.Time   // 更新时间
	DeletedAt      field.Field  // 删除时间
	RoomID         field.Uint   // 会议ID
	CreatorID      field.Uint   // 创建者ID
	Name           field.String // 白板名称
	SnapshotFileID field.Uint   // 快照文件ID
	DataJSON       field.String // 白板数据JSON

	fieldMap map[string]field.Expr
}

func (w whiteboard) Table(newTableName string) *whiteboard {
	w.whiteboardDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w whiteboard) As(alias string) *whiteboard {
	w.whiteboardDo.DO = *(w.whiteboardDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *whiteboard) updateTableName(table string) *whiteboard {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewUint(table, "id")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.UpdatedAt = field.NewTime(table, "updated_at")
	w.DeletedAt = field.NewField(table, "deleted_at")
	w.RoomID = field.NewUint(table, "room_id")
	w.CreatorID = field.NewUint(table, "creator_id")
	w.Name = field.NewString(table, "name")
	w.SnapshotFileID = field.NewUint(table, "snapshot_file_id")
	w.DataJSON = field.NewString(table, "data_json")

	w.fillFieldMap()

	return w
}

func (w *whiteboard) WithContext(ctx context.Context) IWhiteboardDo {
	return w.whiteboardDo.WithContext(ctx)
}

func (w whiteboard) TableName() string { return w.whiteboardDo.TableName() }

func (w whiteboard) Alias() string { return w.whiteboardDo.Alias() }

func (w whiteboard) Columns(cols ...field.Expr) gen.Columns { return w.whiteboardDo.Columns(cols...) }

func (w *whiteboard) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *whiteboard) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 9)
	w.fieldMap["id"] = w.ID
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
	w.fieldMap["deleted_at"] = w.DeletedAt
	w.fieldMap["room_id"] = w.RoomID
	w.fieldMap["creator_id"] = w.CreatorID
	w.fieldMap["name"] = w.Name
	w.fieldMap["snapshot_file_id"] = w.SnapshotFileID
	w.fieldMap["data_json"] = w.DataJSON
}

func (w whiteboard) clone(db *gorm.DB) whiteboard {
	w.whiteboardDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w whiteboard) replaceDB(db *gorm.DB) whiteboard {
	w.whiteboardDo.ReplaceDB(db)
	return w
}

type whiteboardDo struct{ gen.DO }

type IWhiteboardDo interface {
	gen.SubQuery
	Debug() IWhiteboardDo
	WithContext(ctx context.Context) IWhiteboardDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWhiteboardDo
	WriteDB() IWhiteboardDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWhiteboardDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWhiteboardDo
	Not(conds ...gen.Condition) IWhiteboardDo
	Or(conds ...gen.Condition) IWhiteboardDo
	Select(conds ...field.Expr) IWhiteboardDo
	Where(conds ...gen.Condition) IWhiteboardDo
	Order(conds ...field.Expr) IWhiteboardDo
	Distinct(cols ...field.Expr) IWhiteboardDo
	Omit(cols ...field.Expr) IWhiteboardDo
	Join(table schema.Tabler, on ...field.Expr) IWhiteboardDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWhiteboardDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWhiteboardDo
	Group(cols ...field.Expr) IWhiteboardDo
	Having(conds ...gen.Condition) IWhiteboardDo
	Limit(limit int) IWhiteboardDo
	Offset(offset int) IWhiteboardDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWhiteboardDo
	Unscoped() IWhiteboardDo
	Create(values ...*models.Whiteboard) error
	CreateInBatches(values []*models.Whiteboard, batchSize int) error
	Save(values ...*models.Whiteboard) error
	First() (*models.Whiteboard, error)
	Take() (*models.Whiteboard, error)
	Last() (*models.Whiteboard, error)
	Find() ([]*models.Whiteboard, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Whiteboard, err error)
	FindInBatches(result *[]*models.Whiteboard, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Whiteboard) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWhiteboardDo
	Assign(attrs ...field.AssignExpr) IWhiteboardDo
	Joins(fields ...field.RelationField) IWhiteboardDo
	Preload(fields ...field.RelationField) IWhiteboardDo
	FirstOrInit() (*models.Whiteboard, error)
	FirstOrCreate() (*models.Whiteboard, error)
	FindByPage(offset int, limit int) (result []*models.Whiteboard, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWhiteboardDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w whiteboardDo) Debug() IWhiteboardDo {
	return w.withDO(w.DO.Debug())
}

func (w whiteboardDo) WithContext(ctx context.Context) IWhiteboardDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w whiteboardDo) ReadDB() IWhiteboardDo {
	return w.Clauses(dbresolver.Read)
}

func (w whiteboardDo) WriteDB() IWhiteboardDo {
	return w.Clauses(dbresolver.Write)
}

func (w whiteboardDo) Session(config *gorm.Session) IWhiteboardDo {
	return w.withDO(w.DO.Session(config))
}

func (w whiteboardDo) Clauses(conds ...clause.Expression) IWhiteboardDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w whiteboardDo) Returning(value interface{}, columns ...string) IWhiteboardDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w whiteboardDo) Not(conds ...gen.Condition) IWhiteboardDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w whiteboardDo) Or(conds ...gen.Condition) IWhiteboardDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w whiteboardDo) Select(conds ...field.Expr) IWhiteboardDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w whiteboardDo) Where(conds ...gen.Condition) IWhiteboardDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w whiteboardDo) Order(conds ...field.Expr) IWhiteboardDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w whiteboardDo) Distinct(cols ...field.Expr) IWhiteboardDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w whiteboardDo) Omit(cols ...field.Expr) IWhiteboardDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w whiteboardDo) Join(table schema.Tabler, on ...field.Expr) IWhiteboardDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w whiteboardDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWhiteboardDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w whiteboardDo) RightJoin(table schema.Tabler, on ...field.Expr) IWhiteboardDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w whiteboardDo) Group(cols ...field.Expr) IWhiteboardDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w whiteboardDo) Having(conds ...gen.Condition) IWhiteboardDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w whiteboardDo) Limit(limit int) IWhiteboardDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w whiteboardDo) Offset(offset int) IWhiteboardDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w whiteboardDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWhiteboardDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w whiteboardDo) Unscoped() IWhiteboardDo {
	return w.withDO(w.DO.Unscoped())
}

func (w whiteboardDo) Create(values ...*models.Whiteboard) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w whiteboardDo) CreateInBatches(values []*models.Whiteboard, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w whiteboardDo) Save(values ...*models.Whiteboard) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w whiteboardDo) First() (*models.Whiteboard, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Whiteboard), nil
	}
}

func (w whiteboardDo) Take() (*models.Whiteboard, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Whiteboard), nil
	}
}

func (w whiteboardDo) Last() (*models.Whiteboard, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Whiteboard), nil
	}
}

func (w whiteboardDo) Find() ([]*models.Whiteboard, error) {
	result, err := w.DO.Find()
	return result.([]*models.Whiteboard), err
}

func (w whiteboardDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Whiteboard, err error) {
	buf := make([]*models.Whiteboard, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w whiteboardDo) FindInBatches(result *[]*models.Whiteboard, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w whiteboardDo) Attrs(attrs ...field.AssignExpr) IWhiteboardDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w whiteboardDo) Assign(attrs ...field.AssignExpr) IWhiteboardDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w whiteboardDo) Joins(fields ...field.RelationField) IWhiteboardDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w whiteboardDo) Preload(fields ...field.RelationField) IWhiteboardDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w whiteboardDo) FirstOrInit() (*models.Whiteboard, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Whiteboard), nil
	}
}

func (w whiteboardDo) FirstOrCreate() (*models.Whiteboard, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Whiteboard), nil
	}
}

func (w whiteboardDo) FindByPage(offset int, limit int) (result []*models.Whiteboard, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w whiteboardDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w whiteboardDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w whiteboardDo) Delete(models ...*models.Whiteboard) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *whiteboardDo) withDO(do gen.Dao) *whiteboardDo {
	w.DO = *do.(*gen.DO)
	return w
}
